import test from 'node:test';
import assert from 'node:assert/strict';
import {insightCenterMarkup,alertPricingLink,alertWarehouseLink} from '../public/insight-alerts-ui.js';
import {alertOfferingMatches} from '../public/fiyat-hesap-ui.js';
import {scrubAmounts} from '../src/permission-policy.js';
const key='offering:v1:'+JSON.stringify([['food',1000,1,'adet'],['soil',3000,1,'litre']]);
const sale={id:'loss',type:'price',channel:'hepsiburada',key,name:'Besin + toprak seti',kind:'bundle',orders:3,occurrences:3,loss_cents:-30,net_cents:-30,estimated:true,from:'2026-09-05',to:'2026-10-04',samples:[{order_no:'ORDER-1',package_ids:['package-1'],date:'2026-10-04',cash_cents:-10}]};
const stock={product_id:'food',name:'Bitki besini',sku:'FOOD',type:'reorder',stock_unit:'adet',supplier_name:'Tropikal',available_milli:5000,weekly_demand_milli:7000,demand_7_milli:7000,previous_7_milli:7000,days_remaining:5,lead_days:3,cover_days:7,suggested_milli:5000};
test('signal UI links use real channel/immutable composition and order modal parameter',()=>{const html=insightCenterMarkup({sales:{data:{alerts:[sale]}},stock:{data:{alerts:[stock]}}});assert.match(html,/Hepsiburada satış fiyatını yükseltmeyi değerlendir/);assert.match(html,/0,30/);assert.match(html,/Tahmini hesap/);assert.match(html,/ac=package-1/);assert.match(html,/Tropikal için tedarik planını hazırla/);assert.match(html,/Yaklaşık 5 gün/);assert.equal(new URLSearchParams(alertPricingLink(sale).split('?')[1]).get('offering_key'),key);assert.equal(new URLSearchParams(alertWarehouseLink(stock).split('?')[1]).get('tab'),'reorder');});
test('returns and delivery do not recommend price increases; filter separates physical stock',()=>{for(const type of ['returns','delivery']){const html=insightCenterMarkup({sales:{data:{alerts:[{...sale,type}]}},stock:{data:{alerts:[]}}});assert.doesNotMatch(html,/satış fiyatını yükseltmeyi/);assert.doesNotMatch(html,/Fiyatı hesapla/);}const html=insightCenterMarkup({sales:{data:{alerts:[sale]}},stock:{data:{alerts:[stock]}},filter:'stock'});assert.match(html,/data-signal-card="stock"/);assert.doesNotMatch(html,/data-signal-card="price"/);});
test('unknown data and requests never present an all-clear, empty verified data does',()=>{assert.doesNotMatch(insightCenterMarkup({sales:{error:'offline'},stock:{loading:true}}),/Kontrol edilen kayıtlarda uyarı eşiğine/);assert.match(insightCenterMarkup({sales:{data:{alerts:[],partial:true}},stock:{data:{alerts:[]}}}),/bazı satışlar|Bazı satışlar/);assert.match(insightCenterMarkup({sales:{data:{alerts:[]}},stock:{data:{alerts:[]}}}),/Kontrol edilen kayıtlarda uyarı eşiğine/);});
test('marketplace names and supplier text stay inert HTML',()=>{const html=insightCenterMarkup({sales:{data:{alerts:[{...sale,name:'<img src=x onerror=alert(1)>'}]}},stock:{data:{alerts:[{...stock,supplier_name:'<script>steal()</script>'}]}}});assert.doesNotMatch(html,/<img|<script/);assert.match(html,/&lt;img/);});
test('no-amount staff cannot infer losses from names, counts, advice or samples',()=>{const payload={sales_alerts:{alerts:[sale]},cash_cents:500,quantity_milli:1000};const staff={permissions:{ec:{amounts:'none',stock:'read',performance:'read'}}};const result=scrubAmounts(payload,staff,'ec');assert.equal(result.sales_alerts,null);assert.equal(result.cash_cents,null);assert.equal(result.quantity_milli,1000);assert.equal(scrubAmounts(payload,{owner:true},'ec'),payload);});
test('price deep link matches full set and correct channel, never just one stock component',()=>{const offer={channel:'hepsiburada',components:[{product_id:'soil',quantity_milli:3000,stock_unit:'litre'},{product_id:'food',quantity_milli:1000,stock_unit:'adet'}]};assert.equal(alertOfferingMatches(offer,key,'hepsiburada'),true);assert.equal(alertOfferingMatches(offer,key,'trendyol'),false);assert.equal(alertOfferingMatches({...offer,components:offer.components.slice(1)},key,'hepsiburada'),false);assert.equal(alertOfferingMatches(offer,'bad-json','hepsiburada'),false);});

test('stock warning also discloses repeated loss of offerings using this physical product',()=>{const linked={...sale,components:[{product_id:'food'}]};const html=insightCenterMarkup({sales:{data:{alerts:[linked]}},stock:{data:{alerts:[stock]}},filter:'stock'});assert.match(html,/Bu ürünün yer aldığı Hepsiburada satışlarında tekrarlayan zarar da var/);});

test('explicit incomplete sales status suppresses an all-clear without guessed coverage fields',()=>{const html=insightCenterMarkup({sales:{data:{alerts:[],status:'incomplete'}},stock:{data:{alerts:[]}}});assert.doesNotMatch(html,/Kontrol edilen kayıtlarda uyarı eşiğine/);assert.match(html,/Bazı satışlar/);});
