import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {unstable_splitSqlQuery} from 'wrangler';
import {ordersApi,importOrders} from '../src/orders-api.js';
const date='2026-09-09';
function fixture(beforeComponents){
 const sqlite=new DatabaseSync(':memory:');sqlite.exec('PRAGMA foreign_keys=ON');
 for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(n=>n.endsWith('.sql')).sort()){if(file==='0012_order_components.sql')beforeComponents?.(sqlite);const text=readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8');if(file==='0012_order_components.sql')for(const part of unstable_splitSqlQuery(text))sqlite.exec(part);else sqlite.exec(text);}
 const meter={queries:0},raw={prepare(sql){return {values:[],bind(...a){this.values=a;return this;},first(){meter.queries++;return sqlite.prepare(sql).get(...this.values)||null;},all(){meter.queries++;return {results:sqlite.prepare(sql).all(...this.values)};}};},async batch(items){sqlite.exec('BEGIN');try{const result=items.map(x=>x.all());sqlite.exec('COMMIT');return result;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};
 const names=['order_packages','order_lines','order_line_components','order_reservations','order_refresh_audit','provider_records','provider_connections','catalog_mappings','catalog_mapping_components','products','stock_balances','sale_entries'];
 const DB={...raw,prepare(sql){for(const name of names)sql=sql.replace(new RegExp('\\b'+name+'\\b','g'),'ec_'+name);return raw.prepare(sql);}},env={DB,WORKSPACE:'ec'};
 const call=(path='',body)=>ordersApi(new Request('https://test.local/api/orders'+path,{method:body?'POST':'GET'}),env,'/api/orders'+path,async()=>body);
 const product=(key,quantity=100,stockUnit='adet',value=100000)=>{sqlite.prepare('INSERT INTO ec_products(id,name,sku,stock_unit) VALUES(?,?,?,?)').run(key,key,key,stockUnit);sqlite.prepare("INSERT INTO ec_stock_movements(id,product_id,quantity_milli,value_cents,kind,reference,occurred_on) VALUES(?,?,?,?,'opening',?,?)").run('opening:'+key,key,quantity*1000,value,key,date);return key;};
 const mapping=(key,sku,components,source='trendyol')=>{sqlite.prepare("INSERT INTO ec_catalog_mappings(id,source,match_value,external_code,external_name,version) VALUES(?,?,?,?,?,1)").run(key,source,sku,sku,'Farklı ilan adı');for(let i=0;i<components.length;i++){const c=components[i];sqlite.prepare('INSERT INTO ec_catalog_mapping_components(id,mapping_id,product_id,quantity_milli,revenue_share_bps) VALUES(?,?,?,?,?)').run(key+'-c'+i,key,c.product_id,c.quantity_milli,c.revenue_share_bps);}sqlite.prepare('UPDATE ec_catalog_mappings SET active=1 WHERE id=?').run(key);return key;};
 const order=(external,sku,quantity=1,amount=100)=>call('',{channel:'trendyol',external_id:external,occurred_on:date,lines:[{external_id:external+'-L',name:'İlandaki başka ad',sku,quantity,net_revenue:amount}]});
 return {sqlite,env,call,product,mapping,order,meter,close:()=>sqlite.close()};
}
test('Two-pack and mixed bundles reserve aggregate real stock, split revenue exactly and ship once',async()=>{
 const f=fixture();try{
  const a=f.product('A',20,'adet',2000),b=f.product('B',20,'adet',4000);f.mapping('DOUBLE','DOUBLE-A',[{product_id:a,quantity_milli:2000,revenue_share_bps:10000}]);f.mapping('MIX','A-2B',[{product_id:a,quantity_milli:1000,revenue_share_bps:3333},{product_id:b,quantity_milli:2000,revenue_share_bps:6667}]);
  const double=await f.order('O-DOUBLE','DOUBLE-A',2,30),mixed=await f.order('O-MIX','A-2B',3,100.01);let state=await f.call();assert.equal(state.components.find(c=>c.mapping_id==='DOUBLE').quantity_milli,4000);assert.deepEqual(state.components.filter(c=>c.mapping_id==='MIX').map(c=>c.quantity_milli).sort((a,b)=>a-b),[3000,6000]);assert.equal(state.lines.find(l=>l.package_id===mixed.id).product_id,null);assert.equal(state.packages.find(p=>p.id===mixed.id).readiness,'ready');
  await f.call('/'+double.id+'/reserve',{});await f.call('/'+mixed.id+'/reserve',{});state=await f.call();assert.equal(state.products.find(p=>p.id===a).reserved_milli,7000);assert.equal(state.products.find(p=>p.id===b).reserved_milli,6000);
  await f.call('/'+mixed.id+'/ship',{occurred_on:date,reference:'MIX-SHIP'});state=await f.call();assert.equal(state.products.find(p=>p.id===a).quantity_milli,17000);assert.equal(state.products.find(p=>p.id===a).reserved_milli,4000);assert.equal(state.products.find(p=>p.id===b).quantity_milli,14000);const sales=f.sqlite.prepare('SELECT * FROM ec_sale_entries').all();assert.equal(sales.length,2);assert.equal(sales.reduce((n,s)=>n+s.revenue_cents,0),10001);assert.deepEqual(sales.map(s=>s.revenue_cents),[3333,6668]);assert.deepEqual(sales.map(s=>s.cost_cents),[300,1200]);assert.ok(sales.every(s=>s.commission_cents===null));assert.ok(state.components.filter(c=>c.mapping_id==='MIX').every(c=>c.sale_id));
  await f.call('/'+mixed.id+'/ship',{occurred_on:date,reference:'MIX-SHIP'});assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM ec_sale_entries').get().n,2);await f.call('/'+double.id+'/cancel',{reason:'İptal'});assert.equal((await f.call()).reservations.length,0);
 }finally{f.close();}
});
test('Repeated product across listing lines cannot oversell and failed reserve leaves every component untouched',async()=>{
 const f=fixture();try{const a=f.product('A',5),b=f.product('B',100);f.mapping('SET','SET',[{product_id:a,quantity_milli:2000,revenue_share_bps:5000},{product_id:b,quantity_milli:1000,revenue_share_bps:5000}]);const first=await f.call('',{channel:'trendyol',external_id:'REPEAT',occurred_on:date,lines:[{external_id:'L1',name:'Set1',sku:'SET',quantity:2,net_revenue:10},{external_id:'L2',name:'Set2',sku:'SET',quantity:1,net_revenue:10}]});await assert.rejects(f.call('/'+first.id+'/reserve',{}),/stok yetersiz/);const state=await f.call();assert.equal(state.reservations.length,0);assert.equal(state.products.find(p=>p.id===a).quantity_milli,5000);assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM ec_sale_entries').get().n,0);assert.equal(state.packages[0].status,'draft');
 }finally{f.close();}
});
test('Catalog versions do not change existing snapshots; exact provider/code matching and explicit mapping conversion only',async()=>{
 const f=fixture();try{const a=f.product('A'),b=f.product('B'),kg=f.product('KG',10,'kg');f.mapping('OLD','ALIAS',[{product_id:a,quantity_milli:2000,revenue_share_bps:10000}]);const old=await f.order('OLDORDER','ALIAS');f.sqlite.exec("UPDATE ec_catalog_mappings SET active=0,archived_at=CURRENT_TIMESTAMP WHERE id='OLD'");f.mapping('NEW','ALIAS',[{product_id:b,quantity_milli:3000,revenue_share_bps:10000}]);const newer=await f.order('NEWORDER','ALIAS');let state=await f.call();const oldLine=state.lines.find(l=>l.package_id===old.id);assert.equal(state.components.find(c=>c.line_id===oldLine.id).product_id,a);assert.equal(state.components.find(c=>c.line_id===oldLine.id).quantity_milli,2000);assert.equal(state.components.find(c=>c.mapping_id==='NEW').product_id,b);
  const unmapped=await f.order('UNMAPPED','NOT-ALIAS');state=await f.call();const l=state.lines.find(x=>x.package_id===unmapped.id);assert.equal(state.components.some(c=>c.line_id===l.id),false);const km=f.mapping('KG-MAPPING','KG-SET',[{product_id:kg,quantity_milli:500,revenue_share_bps:10000}]);await f.call('/'+unmapped.id+'/map',{lines:[{id:l.id,mapping_id:km}]});state=await f.call();assert.equal(state.components.find(c=>c.line_id===l.id).quantity_milli,500);assert.equal(state.components.find(c=>c.line_id===l.id).stock_unit,'kg');await f.call('/'+unmapped.id+'/reserve',{});await assert.rejects(f.call('/'+unmapped.id+'/map',{lines:[{id:l.id,product_id:a}]}),/taslak/);assert.throws(()=>f.sqlite.exec("UPDATE ec_order_line_components SET quantity_milli=1 WHERE line_id='"+l.id+"'"),/ORDER_LOCKED/);
  const hb=await f.call('',{channel:'hepsiburada',external_id:'HB',occurred_on:date,lines:[{external_id:'HBL',name:'ALIAS',sku:'ALIAS',quantity:1,net_revenue:10}]});state=await f.call();assert.equal(state.packages.find(p=>p.id===hb.id).readiness,'needs_mapping');
 }finally{f.close();}
});
test('Component quantity conversion must be exact and large bundles respect free D1 bound',async()=>{
 const f=fixture();try{
  const ids=Array.from({length:10},(_,i)=>f.product('P'+i,100)),components=ids.map(product_id=>({product_id,quantity_milli:1000,revenue_share_bps:1000}));f.mapping('TEN','TEN',components);const twenty=await f.call('',{channel:'trendyol',external_id:'TWENTY',occurred_on:date,lines:[{external_id:'A',name:'A',sku:'TEN',quantity:1,net_revenue:10},{external_id:'B',name:'B',sku:'TEN',quantity:1,net_revenue:10}]});await f.call('/'+twenty.id+'/reserve',{});f.meter.queries=0;await f.call('/'+twenty.id+'/ship',{occurred_on:date,reference:'20-SHIP'});assert.ok(f.meter.queries<=45,'20-component shipment must leave room for authentication within50queries');assert.equal(f.sqlite.prepare('SELECT COUNT(*) n FROM ec_sale_entries').get().n,20);
  await assert.rejects(f.call('',{channel:'trendyol',external_id:'THIRTY',occurred_on:date,lines:[0,1,2].map(i=>({external_id:'L'+i,name:'Set',sku:'TEN',quantity:1,net_revenue:10}))}),/20 stok bileşeni/);assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM ec_order_packages WHERE external_id='THIRTY'").get().n,0);
  const kg=f.product('KG',10,'kg');f.mapping('FRAC','FRACTION',[{product_id:kg,quantity_milli:500,revenue_share_bps:10000}],'other');await assert.rejects(f.call('',{channel:'other',external_id:'FRACTION',occurred_on:date,lines:[{external_id:'F',sku:'FRACTION',name:'Kesir',quantity:0.001,net_revenue:10}]}),/tam olarak dönüştürülemiyor/);
 }finally{f.close();}
});
test('Migration preserves pre-existing reserved and shipped one-to-one orders and sale links',()=>{
 const f=fixture(db=>{db.exec("INSERT INTO ec_products(id,name,sku) VALUES('OLD-P','Eski','OLD-P'); INSERT INTO ec_stock_movements(id,product_id,quantity_milli,value_cents,kind,reference,occurred_on) VALUES('OLD-ST','OLD-P',10000,10000,'opening','OLD','2026-09-09'); INSERT INTO ec_order_packages(id,channel,external_id,occurred_on,source_fingerprint) VALUES('HOLD','trendyol','HOLD','2026-09-09','old'),('SENT','trendyol','SENT','2026-09-09','old'); INSERT INTO ec_order_lines(id,package_id,external_id,name,product_id,quantity_milli,net_revenue_cents) VALUES('HOLD-L','HOLD','HL','Eski','OLD-P',2000,2000),('SENT-L','SENT','SL','Eski','OLD-P',1000,1000); UPDATE ec_order_packages SET status='reserved' WHERE id IN ('HOLD','SENT'); UPDATE ec_order_packages SET status='shipped',shipment_reference='OLD-REF',shipped_on='2026-09-09' WHERE id='SENT'; INSERT INTO ec_sale_entries(id,channel,external_id,product_id,kind,quantity_milli,revenue_cents,cost_cents,fees_status,occurred_on) VALUES('OLD-SALE','trendyol','old-sale','OLD-P','sale',1000,1000,1000,'pending','2026-09-09'); UPDATE ec_order_lines SET sale_id='OLD-SALE' WHERE id='SENT-L';");});try{
  assert.equal(f.sqlite.prepare("SELECT quantity_milli FROM ec_stock_balances WHERE product_id='OLD-P'").get().quantity_milli,9000);assert.equal(f.sqlite.prepare("SELECT SUM(quantity_milli) n FROM ec_order_reservations WHERE released_on IS NULL").get().n,2000);assert.equal(f.sqlite.prepare("SELECT sale_id FROM ec_order_line_components WHERE line_id='SENT-L'").get().sale_id,'OLD-SALE');assert.equal(f.sqlite.prepare("SELECT COUNT(*) n FROM ec_sale_entries").get().n,1);assert.deepEqual(f.sqlite.prepare('PRAGMA foreign_key_check').all(),[]);
 }finally{f.close();}
});
