import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile} from 'node:fs/promises';
import {appFixture} from './helpers/app-fixture.js';
import worker from '../src/worker.js';
import {hash} from '../src/access-api.js';
import {findPlaywright} from '../scripts/design-audit.mjs';
import {PDFDocument} from 'pdf-lib';
const enabled=process.env.PARTY_PROFILE_BROWSER==='1';
const restricted={id:'pp-reader',owner:false,ec_access:'read',lp_access:'read',permissions:{ec:{ledger:'read',invoices:'read',amounts:'none'},lp:{ledger:'read',accounts:'read',amounts:'none'}}};
const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jWZ0AAAAASUVORK5CYII=','base64');

test('isolated cari browser: real edits, reminders, file upload/view, permissions and disposal',{skip:!enabled,timeout:150000},async t=>{
 const f=appFixture();await f.setup();const auth=await f.req('/auth/login',{password:'synthetic-owner-password'});
 for(const ns of ['ec','lp']){f.sqlite.prepare(`INSERT INTO ${ns}_suppliers(id,name,contact) VALUES('browser-party',?,?)`).run('Örnek cari <script>','Sentetik kişi');f.sqlite.prepare(`INSERT INTO ${ns}_party_entries(id,party_id,amount_cents,occurred_on,reference,description,source_key,source) VALUES('debt','browser-party',-12345,'2026-01-01','BORC','Test','debt','manual')`).run();}
 f.sqlite.prepare('INSERT INTO staff_users(id,username,name,ec_access,lp_access,permissions_json) VALUES(?,?,?,?,?,?)').run(restricted.id,'pp-reader','Sınırlı kişi','read','read',JSON.stringify(restricted.permissions));
 f.sqlite.prepare('UPDATE staff_users SET password_hash=?,salt=? WHERE id=?').run('synthetic-test-hash','synthetic',restricted.id);const readerToken='ab'.repeat(32);f.sqlite.prepare('INSERT INTO sessions(token_hash,expires_at,staff_id) VALUES(?,?,?)').run(await hash(readerToken),Math.floor(Date.now()/1000)+3600,restricted.id);
 f.env.ASSETS={async fetch(request){const path=new URL(request.url).pathname;
  if(path==='/test')return new Response('<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Cari test</title><link rel="stylesheet" href="/test-frame.css"><link rel="stylesheet" href="/party-profile.css"><main id="root"></main><script type="module" src="/test-entry.js"></script></html>',{headers:{'Content-Type':'text/html'}});
  if(path==='/test-frame.css')return new Response('body{margin:0;font-family:Arial,sans-serif}main{min-width:0}',{headers:{'Content-Type':'text/css'}});
  if(path==='/test-entry.js')return new Response(`import {mountPartyProfile} from '/party-profile-ui.js';const q=new URLSearchParams(location.search);window.ppUser=q.get('role')==='reader'?${JSON.stringify(restricted)}:{owner:true};window.ppDispose=mountPartyProfile(document.querySelector('#root'),q.get('ns')||'ec',window.ppUser);`,{headers:{'Content-Type':'text/javascript'}});
  if(['/party-profile-ui.js','/party-profile.css','/permissions.js'].includes(path))return new Response(await readFile(new URL('../public'+path,import.meta.url)),{headers:{'Content-Type':path.endsWith('.css')?'text/css':'text/javascript'}});
  return new Response('',{status:404});
 }};
 let origin;const server=createServer((req,res)=>{(async()=>{const chunks=[];for await(const chunk of req)chunks.push(chunk);const response=await worker.fetch(new Request(origin+req.url,{method:req.method,headers:req.headers,...(!['GET','HEAD'].includes(req.method)?{body:Buffer.concat(chunks)}:{})}),f.env);res.writeHead(response.status,Object.fromEntries(response.headers));res.end(Buffer.from(await response.arrayBuffer()));})().catch(e=>{res.writeHead(500);res.end(e.message);});});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));origin='http://127.0.0.1:'+server.address().port;
 const {api}=await findPlaywright();assert.ok(api,'Installed browser driver required');const browser=await api.chromium.launch({headless:true,channel:'chrome'}),errors=[],blocked=[];
 async function context(role='owner',width=390){const c=await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});const pair=role==='owner'?auth.cookie:'lunapot_session='+readerToken,eq=pair.indexOf('=');await c.addCookies([{name:pair.slice(0,eq),value:pair.slice(eq+1),url:origin}]);await c.route('**/*',route=>{const u=new URL(route.request().url());if(['http:','https:'].includes(u.protocol)&&u.origin!==origin){blocked.push(u.href);return route.abort();}return route.continue();});const p=await c.newPage();p.setDefaultTimeout(7000);p.on('pageerror',e=>errors.push(e.message));return {c,p};}
 const go=(p,ns,role='owner')=>p.goto(origin+'/test?'+new URLSearchParams({ns,role})+'#party?id=browser-party');
 const tab=async(p,id)=>{await p.locator(`.pp-tabs [data-pp="tab"][data-tab="${id}"]`).click();await p.locator('.pp-content[aria-busy="true"]').waitFor({state:'detached'});};
 const noOverflow=async p=>assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false);
 try{
  for(const ns of ['ec','lp'])await t.test(ns+' edit/save/reopen, conflict retains draft, notes and attachment round trip',async()=>{const {c,p}=await context();try{
   await go(p,ns);await p.locator('.pp-metric').first().waitFor();assert.equal(await p.locator('.pp-tabs button').count(),6);assert.equal(await p.locator('h1').innerText(),'Örnek cari <script>');assert.equal(await p.locator('#root script').count(),0);await noOverflow(p);
   await tab(p,'info');await p.locator('[data-pp="edit"]').click();await p.locator('[name="legal_name"]').fill('Lunapot Deneme Ltd');await p.locator('[name="trade_name"]').fill('Yeni ticari ad');await p.locator('[name="tax_office"]').fill('Şişli');await p.locator('[name="payment_terms_days"]').fill('30');await p.locator('[name="min_order"]').fill('125.65');await p.locator('[name="discount"]').fill('1.25');
   await p.locator('[data-pp="add-row"][data-kind="contacts"]').click();await p.locator('[name="contacts.0.name"]').fill('Ayşe');await p.locator('[name="contacts.0.email"]').fill('ayse@example.test');await p.locator('[data-pp="add-row"][data-kind="addresses"]').click();await p.locator('[name="addresses.0.label"]').fill('Depo');await p.locator('[name="addresses.0.address"]').fill('Sentetik adres');await p.locator('[data-pp="add-row"][data-kind="banks"]').click();await p.locator('[name="banks.0.bank_name"]').fill('Test Banka');await p.locator('[name="banks.0.iban"]').fill('TR330006100519786457841326');await noOverflow(p);
   await p.locator('[data-pp-form="profile"] [type="submit"]').click();await p.getByText('Bilgiler kaydedildi.',{exact:true}).waitFor();let row=f.sqlite.prepare(`SELECT * FROM ${ns}_party_profiles WHERE party_id='browser-party'`).get();assert.equal(row.min_order_cents,12565);assert.equal(row.discount_bps,125);assert.equal(row.revision,1);assert.equal(JSON.parse(row.contacts_json)[0].name,'Ayşe');
   await p.reload();await p.locator('.pp-metric').first().waitFor();await tab(p,'info');await p.getByText('Lunapot Deneme Ltd',{exact:true}).waitFor();await p.locator('[data-pp="edit"]').click();await p.locator('[name="legal_name"]').fill('Stale unsaved draft');const concurrent=await c.request.post(origin+'/api/'+ns+'/party-profiles/browser-party',{headers:{Origin:origin},data:{expected_revision:1,lead_days:9}});assert.equal(concurrent.status(),200);await p.locator('[data-pp-form="profile"] [type="submit"]').click();await p.locator('[data-pp-form-error]').filter({hasText:'başka bir işlemde değişti'}).waitFor();assert.equal(await p.locator('[name="legal_name"]').inputValue(),'Stale unsaved draft');assert.equal(f.sqlite.prepare(`SELECT legal_name FROM ${ns}_party_profiles`).get().legal_name,'Lunapot Deneme Ltd');await p.locator('[data-pp="reload"]').click();await p.getByText('Lunapot Deneme Ltd',{exact:true}).waitFor();
   await tab(p,'documents');await p.locator('[name="body"]').fill('Fiyat 999 TL <img src=x onerror=alert(1)>');await p.locator('[name="remind_on"]').fill('2026-12-20');await p.locator('[data-pp-form="note"] [type="submit"]').click();await p.getByText('Bilgiler kaydedildi.',{exact:true}).waitFor();assert.equal(await p.locator('.pp-line img').count(),0);await p.locator('[data-pp="note-status"]').click();await p.locator('[data-pp="note-status"]').filter({hasText:'Yeniden aç'}).waitFor();assert.equal(f.sqlite.prepare(`SELECT status FROM ${ns}_party_profile_notes`).get().status,'done');
   await p.locator('[name="file"]').setInputFiles({name:'cari-belge.png',mimeType:'image/png',buffer:png});await p.locator('[data-pp-form="upload"] [type="submit"]').click();await p.getByText('Dosya yüklendi ve doğrulandı.',{exact:true}).waitFor();const file=f.sqlite.prepare(`SELECT * FROM ${ns}_party_profile_files`).get();assert.equal(file.state,'sealed');assert.equal(file.revision,3);assert.deepEqual(Buffer.from(f.sqlite.prepare(`SELECT data_b64 FROM ${ns}_party_profile_file_chunks WHERE file_id=?`).get(file.id).data_b64,'base64'),png);
   await p.locator('[data-pp="file"]').click();await p.locator('dialog[open]').waitFor();await p.waitForFunction(()=>document.querySelector('dialog img')?.naturalWidth===1);assert.equal(await p.locator('dialog [download]').getAttribute('download'),'cari-belge.png');await p.locator('[data-pp="close-file"]').click();await p.locator('dialog').waitFor({state:'detached'});
   await p.reload();await p.locator('.pp-metric').first().waitFor();await tab(p,'documents');await p.getByText('cari-belge.png',{exact:true}).waitFor();await p.locator('[data-pp="file"]').click();await p.locator('dialog[open]').waitFor();await p.keyboard.press('Escape');const pdf=await PDFDocument.create();pdf.addPage().drawText('Synthetic cari document');const pdfBytes=Buffer.from(await pdf.save());await p.locator('[name="file"]').setInputFiles({name:'cari-belge.pdf',mimeType:'application/pdf',buffer:pdfBytes});await p.locator('[data-pp-form="upload"] [type="submit"]').click();await p.getByText('Dosya yüklendi ve doğrulandı.',{exact:true}).waitFor();await p.locator('.pp-line').filter({hasText:'cari-belge.pdf'}).locator('[data-pp="file"]').click();await p.locator('dialog object[type="application/pdf"]').waitFor();assert.match(await p.locator('dialog object').getAttribute('data'),/^blob:/);await p.locator('[data-pp="close-file"]').click();await noOverflow(p);assert.equal(await p.evaluate(()=>localStorage.length),0);
  }finally{await c.close();}});
  await t.test('read-only amount-restricted user cannot see/edit sensitive metadata',async()=>{const {c,p}=await context('reader',320);try{await go(p,'ec','reader');await p.locator('.pp-metric').first().waitFor();assert.equal(await p.locator('.pp-metric strong').first().innerText(),'Tutar gizli');assert.equal(await p.getByText('Ödeme kaydet',{exact:true}).count(),0);await tab(p,'info');assert.equal(await p.locator('[data-pp="edit"]').count(),0);assert.doesNotMatch(await p.locator('#root').innerText(),/TR330006|Test Banka/);await tab(p,'documents');await p.getByText('Dosya ve notlarda tutar bulunabilir. Görmek için tutar yetkisi gerekli.').waitFor();assert.equal(await p.locator('[name="file"]').count(),0);assert.doesNotMatch(await p.locator('#root').innerText(),/999 TL|cari-belge.png/);await noOverflow(p);}finally{await c.close();}});
  await t.test('disposal ignores a late response and removes handlers',async()=>{const {c,p}=await context();try{await c.route('**/api/ec/party-profiles/browser-party',async route=>{await new Promise(r=>setTimeout(r,250));try{await route.continue();}catch{}});await go(p,'ec');await p.evaluate(()=>{window.ppDispose();document.querySelector('#root').textContent='Yeni ekran';});await p.waitForTimeout(450);assert.equal(await p.locator('#root').innerText(),'Yeni ekran');}finally{await c.close();}});
  assert.deepEqual(errors,[]);assert.deepEqual(blocked,[]);
 }finally{await browser.close();await new Promise(resolve=>server.close(resolve));f.close();}
});
