import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
import {scopedDB} from '../src/scoped-db.js';
import {accountingApi} from '../src/accounting.js';
import {purchaseSplitApi} from '../src/purchase-split-api.js';
function fixture(){const s=new DatabaseSync(':memory:');s.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort())s.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));const DB={prepare(sql){return {args:[],bind(...args){this.args=args;return this;},first(){return s.prepare(sql).get(...this.args)||null;},all(){return {results:s.prepare(sql).all(...this.args)};},run(){return s.prepare(sql).run(...this.args);}};},async batch(items){s.exec('BEGIN');try{const r=items.map(i=>i.all());s.exec('COMMIT');return r;}catch(e){s.exec('ROLLBACK');throw e;}}};const call=(handler,ns,path,body)=>handler(new Request('https://test.local'+path,{method:body===undefined?'GET':'POST'}),{DB:scopedDB(DB,ns),ROOT_DB:DB,WORKSPACE:ns},path,async()=>body);const ac=(path,body,ns='ec')=>call(accountingApi,ns,'/api/accounting'+path,body),split=(path,body,ns='ec')=>call(purchaseSplitApi,ns,'/api/invoices/'+path,body);return {s,DB,ac,split,call};}
async function setup(f){const supplier=(await f.ac('/suppliers',{name:'Test Tedarikçisi'})).id;const products=[];for(let i=0;i<5;i++)products.push((await f.ac('/products',{name:'Çeşit '+i,sku:'V'+i,stock_unit:'adet',min_stock:0})).id);const inv=(await f.ac('/invoices',{supplier_id:supplier,invoice_no:'MIX',invoice_date:'2026-09-09',currency:'TRY',lines:[{description:'Karışık ürün',external_code:'MIX-100',invoice_quantity:100,invoice_unit:'adet',net:1000.01,tax:200.01}]})).id;const line=(await f.ac('/invoices/'+inv)).lines[0];return {inv,line,products,body:{line_id:line.id,total_quantity:100,reason:'İrsaliye dökümü TEST',equal_unit_cost:true,allocations:products.map((p,i)=>({product_id:p,quantity:[20,15,25,10,30][i]}))}};}
test('Five physical variants preserve original supplier line, invoice totals, one payable and receipt stock',async()=>{const f=fixture();try{const x=await setup(f);await f.split(x.inv+'/split',x.body);const inv=await f.ac('/invoices/'+x.inv);assert.equal(inv.lines.length,5);assert.equal(inv.splits[0].original.description,'Karışık ürün');assert.equal(inv.lines.reduce((s,l)=>s+l.net_cents,0),100001);assert.equal(inv.lines.reduce((s,l)=>s+l.tax_cents,0),20001);assert.equal(inv.lines.reduce((s,l)=>s+l.invoice_quantity,0),100);await f.ac('/invoices/'+x.inv+'/post',{});assert.equal(f.s.prepare('SELECT COUNT(*) n FROM ec_party_entries').get().n,1);assert.equal(f.s.prepare('SELECT SUM(amount_cents) n FROM ec_party_entries').get().n,-120002);await f.ac('/invoices/'+x.inv+'/receive',{reference:'RECEIPT-1',occurred_on:'2026-09-09',lines:inv.lines.map(l=>({id:l.id,quantity:l.quantity_milli/1000}))});assert.equal(f.s.prepare('SELECT SUM(value_cents) n FROM ec_stock_balances').get().n,100001);assert.deepEqual(f.s.prepare('SELECT quantity_milli FROM ec_stock_balances ORDER BY product_id').all().map(r=>r.quantity_milli).sort((a,b)=>a-b),[10000,15000,20000,25000,30000]);await assert.rejects(f.split(x.inv+'/splits/'+inv.splits[0].id+'/undo',{}),e=>e.status===409);}finally{f.s.close();}});
test('Variant split rejects totals, duplicate products, wrong scope and repeat; undo restores exact original draft',async()=>{const f=fixture();try{const x=await setup(f);await assert.rejects(f.split(x.inv+'/split',{...x.body,total_quantity:101}),e=>e.status===400);await assert.rejects(f.split(x.inv+'/split',{...x.body,allocations:[x.body.allocations[0],x.body.allocations[0]]}),e=>e.status===400);await assert.rejects(f.split(x.inv+'/split',x.body,'lp'),e=>e.status===404);const a=await f.split(x.inv+'/split',x.body);await assert.rejects(f.split(x.inv+'/split',x.body),e=>e.status===409);await f.split(x.inv+'/splits/'+a.split_id+'/undo',{});const restored=(await f.ac('/invoices/'+x.inv)).lines;assert.equal(restored.length,1);for(const k of ['id','description','external_code','product_id','quantity_milli','net_cents','tax_cents','invoice_quantity'])assert.equal(restored[0][k],x.line[k]);await f.split(x.inv+'/split',x.body);assert.equal((await f.ac('/invoices/'+x.inv)).splits.length,2);}finally{f.s.close();}});
import {productionApi} from '../src/production-api.js';
async function productionSetup(f){f.s.exec("INSERT INTO materials(id,name,unit,price) VALUES('m1','Test reçine','kg',99),('m2','Test pigment','g',2);INSERT INTO products(id,name,sku) VALUES('p1','Test mamul','P1');INSERT INTO recipes(id,product_id,yield_qty,waste_pct,labor,packaging,overhead) VALUES('r1','p1',10,10,20,10,5);INSERT INTO recipe_items(id,recipe_id,material_id,quantity,unit) VALUES('i1','r1','m1',2,'kg'),('i2','r1','m2',100,'g');");const prod=(path,body,ns='lp')=>f.call(productionApi,ns,'/api/production'+path,body);for(const [id,q,c] of [['m1',10,50],['m2',1000,1]])await prod('/material-stock',{material_id:id,kind:'opening',quantity:q,unit_cost:c,reference:'OPEN-'+id,notes:'Başlangıç',occurred_on:'2026-09-09'});return {prod,body:{recipe_id:'r1',quantity:10,labor:20,packaging:10,overhead:5,reference:'PARTI-1',notes:'Gerçek üretim',occurred_on:'2026-09-09',items:[{material_id:'m1',quantity:2.5},{material_id:'m2',quantity:120}]}};}
test('Production consumes actual materials atomically, capitalizes overhead and freezes cost independently of recipe prices',async()=>{const f=fixture();try{const {prod,body}=await productionSetup(f);const job=await prod('/jobs',body);assert.equal(job.total_cost_cents,28000);assert.deepEqual({...f.s.prepare("SELECT quantity_milli,value_cents FROM lp_stock_balances WHERE product_id='p1'").get()},{quantity_milli:10000,value_cents:28000});assert.equal(f.s.prepare("SELECT quantity_milli FROM lp_material_balances WHERE material_id='m1'").get().quantity_milli,7500);assert.equal(f.s.prepare("SELECT COUNT(*) n FROM ec_stock_movements").get().n,0);assert.equal(f.s.prepare("SELECT COUNT(*) n FROM lp_expenses").get().n,0);f.s.exec("UPDATE materials SET price=999 WHERE id='m1'; UPDATE recipes SET labor=999 WHERE id='r1';");const detail=await prod('/jobs/'+job.id);assert.equal(detail.job.total_cost_cents,28000);assert.equal(detail.items.find(i=>i.material_id==='m1').planned_milli,2200);await assert.rejects(prod('/jobs',body),e=>e.status===409);await assert.rejects(prod('/jobs',body,'ec'),e=>e.status===403);await prod('/jobs/'+job.id+'/reverse',{occurred_on:'2026-09-09',reason:'Yanlış parti kaydı'});assert.equal(f.s.prepare("SELECT quantity_milli FROM lp_stock_balances WHERE product_id='p1'").get().quantity_milli,0);assert.equal(f.s.prepare("SELECT quantity_milli FROM lp_material_balances WHERE material_id='m1'").get().quantity_milli,10000);await assert.rejects(prod('/jobs/'+job.id+'/reverse',{occurred_on:'2026-09-09',reason:'Tekrar'}),e=>e.status===409);}finally{f.s.close();}});
test('Production shortage and reversing sold output do not leave partial stock or material movements',async()=>{const f=fixture();try{const {prod,body}=await productionSetup(f);await assert.rejects(prod('/jobs',{...body,items:[{material_id:'m1',quantity:20},{material_id:'m2',quantity:120}]}),e=>e.status===409);assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_production_jobs').get().n,0);const job=await prod('/jobs',body);await f.ac('/sales',{channel:'other',external_id:'SOLD',product_id:'p1',quantity:1,revenue:50,commission:0,shipping:0,other:0,fees_status:'confirmed',occurred_on:'2026-09-09'},'lp');await assert.rejects(prod('/jobs/'+job.id+'/reverse',{occurred_on:'2026-09-09',reason:'Hatalı'}),e=>e.status===409);assert.equal((await prod('/jobs/'+job.id)).job.status,'posted');assert.equal(f.s.prepare("SELECT quantity_milli FROM lp_material_balances WHERE material_id='m1'").get().quantity_milli,7500);await assert.rejects(prod('/material-stock',{material_id:'m1',kind:'opening',quantity:10,unit_cost:50,reference:'OTHER-OPEN',notes:'Tekrar',occurred_on:'2026-09-09'}),e=>e.status===409);assert.throws(()=>f.s.exec("UPDATE materials SET unit='g' WHERE id='m1'"),/MATERIAL_UNIT_LOCKED/);}finally{f.s.close();}});
import {catalogApi} from '../src/catalog-api.js';
import worker from '../src/worker.js';
import {unstable_splitSqlQuery} from 'wrangler';
test('Supplier brands feed one material card; invoice receipt, recipe consumption and count share inventory once',async()=>{const f=fixture();try{f.s.exec("INSERT INTO materials(id,name,unit,price) VALUES('poly','Polyester','kg',99)");const card=f.s.prepare("SELECT purchase_product_id FROM materials WHERE id='poly'").get().purchase_product_id;for(const [brand,cost] of [['Marka A',50],['Marka B',70]]){const supplier=(await f.ac('/suppliers',{name:brand},'lp')).id;await f.call(catalogApi,'lp','/api/catalog/mappings',{source:'purchase',supplier_id:supplier,external_code:brand,source_unit:'kg',components:[{product_id:card,quantity_milli:1000,revenue_share_bps:10000}]});const inv=(await f.ac('/invoices',{supplier_id:supplier,invoice_no:brand,invoice_date:'2026-09-09',currency:'TRY',lines:[{description:brand+' polyester',external_code:brand,invoice_quantity:10,invoice_unit:'kg',net:10*cost,tax:0}]},'lp')).id;const line=(await f.ac('/invoices/'+inv,undefined,'lp')).lines[0];assert.equal(line.product_id,card);await f.ac('/invoices/'+inv+'/post',{},'lp');await f.ac('/invoices/'+inv+'/receive',{reference:brand,occurred_on:'2026-09-09',lines:[{id:line.id,quantity:10}]},'lp');}assert.deepEqual({...f.s.prepare("SELECT quantity_milli,value_cents FROM lp_material_balances WHERE material_id='poly'").get()},{quantity_milli:20000,value_cents:120000});assert.deepEqual({...f.s.prepare('SELECT quantity_milli,value_cents FROM lp_stock_balances WHERE product_id=?').get(card)},{quantity_milli:20000,value_cents:120000});assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_material_movements').get().n,2);await f.call(productionApi,'lp','/api/production/material-stock',{material_id:'poly',kind:'count',quantity:19,reference:'COUNT',notes:'Gerçek sayım',occurred_on:'2026-09-09'});assert.equal(f.s.prepare('SELECT SUM(amount_cents) n FROM lp_expenses').get().n,6000);assert.equal(f.s.prepare('SELECT quantity_milli FROM lp_stock_balances WHERE product_id=?').get(card).quantity_milli,19000);assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_party_entries').get().n,2);}finally{f.s.close();}});
test('60-material recipe creation and production stay within bounded query budget',async()=>{const f=fixture();try{const origin='https://test.local',env={DB:f.DB,SETUP_TOKEN:'local-only-setup'};const setup=await worker.fetch(new Request(origin+'/api/auth/setup',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({token:env.SETUP_TOKEN,password:'local-only-test-password'})}),env);const cookie=setup.headers.get('set-cookie').split(';')[0];f.s.exec("INSERT INTO products(id,name,sku) VALUES('output60','60 materyalli mamul','OUT60')");const items=[];for(let i=0;i<60;i++){const id='mat-'+i;f.s.prepare('INSERT INTO materials(id,name,unit,price) VALUES(?,?,?,?)').run(id,'Hammadde '+i,'kg',10);f.s.prepare("INSERT INTO lp_material_movements(id,material_id,quantity_milli,value_cents,kind,reference,notes,occurred_on) VALUES(?,?,10000,10000,'opening',?,'Test','2026-09-09')").run('open-'+i,id,'open-'+i);items.push({material_id:id,quantity:1,unit:'kg'});}let calls=0;const prepare=f.DB.prepare.bind(f.DB);f.DB.prepare=sql=>{const q=prepare(sql);for(const name of ['first','all','run']){const old=q[name].bind(q);q[name]=()=>{calls++;return old();};}return q;};const response=await worker.fetch(new Request(origin+'/api/recipes',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie},body:JSON.stringify({product_id:'output60',yield_qty:10,waste_pct:0,labor:0,packaging:0,overhead:0,items})}),env);const result=await response.json();assert.equal(response.status,201,JSON.stringify(result));assert.ok(calls<15,'recipe queries: '+calls);calls=0;const job=await f.call(productionApi,'lp','/api/production/jobs',{recipe_id:result.id,quantity:10,labor:0,packaging:0,overhead:0,reference:'60-MAT',notes:'60 kalem testi',occurred_on:'2026-09-09',items:items.map(i=>({material_id:i.material_id,quantity:1}))});assert.equal(job.total_cost_cents,60000);assert.ok(calls<15,'production queries: '+calls);assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_production_items').get().n,60);assert.equal(f.s.prepare("SELECT COUNT(*) n FROM lp_material_balances WHERE quantity_milli=9000").get().n,60);}finally{f.s.close();}});
test('New inventory migrations survive Wrangler statement splitting including existing raw stock',()=>{const s=new DatabaseSync(':memory:');try{s.exec('PRAGMA foreign_keys=ON');for(const file of readdirSync(new URL('../migrations/',import.meta.url)).filter(f=>f.endsWith('.sql')).sort()){if(file.startsWith('0018')){s.exec("INSERT INTO materials(id,name,unit,price) VALUES('preexisting','Önceki stok','kg',1); INSERT INTO lp_material_movements(id,material_id,quantity_milli,value_cents,kind,reference,notes,occurred_on) VALUES('pre-open','preexisting',1000,150,'opening','PRE','Test','2026-09-09')");}const text=readFileSync(new URL('../migrations/'+file,import.meta.url),'utf8');if(file>='0016')for(const statement of unstable_splitSqlQuery(text))s.exec(statement);else s.exec(text);}assert.equal(s.prepare("SELECT quantity_milli FROM lp_stock_balances WHERE product_id='raw-preexisting'").get().quantity_milli,1000);assert.equal(s.prepare("SELECT quantity_milli FROM lp_material_balances WHERE material_id='preexisting'").get().quantity_milli,1000);assert.equal(s.prepare('SELECT COUNT(*) n FROM lp_material_movements').get().n,1);}finally{s.close();}});

// ---- Üretimden otomatik parti (lot). Parti stok değiştirmez; üretimle aynı işlemde yazılır. ----
test('Üretim kaydı isteğe bağlı olarak partiyi aynı işlemde açar; seçilmezse parti açılmaz', async () => {
  const f = fixture(); try {
    const {prod, body} = await productionSetup(f);
    const job = await prod('/jobs', {...body, create_lot: 'on', best_before: '2027-09-09', pack_size: 4});
    assert.match(job.lot_code, /^2026-09-P001$/);
    const lot = {...f.s.prepare('SELECT lot_code,product_id,job_id,produced_on,best_before,quantity_milli,unit,pack_size_milli,status FROM lp_lots').get()};
    assert.deepEqual(lot, {lot_code: '2026-09-P001', product_id: 'p1', job_id: job.id, produced_on: '2026-09-09', best_before: '2027-09-09',
      quantity_milli: 10000, unit: 'adet', pack_size_milli: 4000, status: 'open'});
    const stock = f.s.prepare("SELECT quantity_milli FROM lp_stock_balances WHERE product_id='p1'").get().quantity_milli;
    const plain = await prod('/jobs', {...body, reference: 'PARTI-2'});
    assert.equal(plain.lot_code, null);
    assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_lots').get().n, 1, 'seçilmeyen üretimde parti yok');
    assert.equal(f.s.prepare("SELECT quantity_milli FROM lp_stock_balances WHERE product_id='p1'").get().quantity_milli, stock + 10000, 'parti stoğu ikinci kez artırmaz');
  } finally { f.s.close(); }
});

test('Parti kodu çakışırsa ya da son kullanma üretimden önceyse üretim de yazılmaz', async () => {
  const f = fixture(); try {
    const {prod, body} = await productionSetup(f);
    await prod('/jobs', {...body, create_lot: 'on', lot_code: 'LOT-A'});
    const jobs = () => f.s.prepare('SELECT COUNT(*) n FROM lp_production_jobs').get().n;
    const before = jobs();
    await assert.rejects(prod('/jobs', {...body, reference: 'PARTI-3', create_lot: 'on', lot_code: 'LOT-A'}), e => e.status === 409);
    await assert.rejects(prod('/jobs', {...body, reference: 'PARTI-4', create_lot: 'on', best_before: '2026-01-01'}), e => e.status === 400);
    await assert.rejects(prod('/jobs', {...body, reference: 'PARTI-5', create_lot: 'on', lot_code: '-kotu kod'}), e => e.status === 400);
    assert.equal(jobs(), before, 'reddedilen parti üretim kaydı bırakmaz');
    assert.equal(f.s.prepare('SELECT COUNT(*) n FROM lp_lots').get().n, 1);
  } finally { f.s.close(); }
});
