import test from 'node:test';import assert from 'node:assert/strict';import{DatabaseSync}from'node:sqlite';import{readFileSync,readdirSync}from'node:fs';import worker from'../src/worker.js';import{LEGAL_VERSION}from'../src/webshop-legal.js';import{permit}from'../src/permission-policy.js';
function db(){const s=new DatabaseSync(':memory:');s.exec('PRAGMA foreign_keys=ON');for(const f of readdirSync(new URL('../migrations/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())s.exec(readFileSync(new URL('../migrations/'+f,import.meta.url),'utf8'));s.exec("INSERT INTO ws_catalog VALUES('soil-standard','soil','Toprak','Standart','soil.webp','toprak',19000,3,1)");const prepare=sql=>({v:[],bind(...v){this.v=v;return this},first(){return s.prepare(sql).get(...this.v)||null},all(){return{results:s.prepare(sql).all(...this.v)}},run(){return s.prepare(sql).run(...this.v)}});return{prepare,batch:async items=>{s.exec('BEGIN');try{const r=items.map(i=>i.all());s.exec('COMMIT');return r}catch(e){s.exec('ROLLBACK');throw e}},close:()=>s.close()}}
function client(DB){let cookie='';const env={DB,WS_MODE:'demo'},origin='http://localhost';return{env,get cookie(){return cookie},async req(path,method='GET',body,extra={}){const r=await worker.fetch(new Request(origin+'/api'+path,{method,headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,...extra},...(body?{body:JSON.stringify(body)}:{})}),env);if(r.headers.get('Set-Cookie'))cookie=r.headers.get('Set-Cookie').split(';')[0];return{status:r.status,data:await r.json(),headers:r.headers}}}}
const address={name:'Test Müşteri',phone:'05000000000',city:'İstanbul',district:'Şişli',line:'Test adresi No 1'};const signup=(c,n='one')=>c.req('/store/auth/register','POST',{email:n+'@example.test',name:'Test '+n,password:'local-test-password-123',terms_version:LEGAL_VERSION});const quote=(c,qty=1)=>c.req('/store/quote','POST',{items:[{variant_id:'soil-standard',qty,price_cents:1}],address,same_billing:true});const order=(c,id)=>c.req('/store/orders','POST',{quote_id:id,legal_version:LEGAL_VERSION,preinformation:true,contract:true});
test('web shop auth is separate, origin protected, closed on live hosts',async()=>{const DB=db();try{const c=client(DB);assert.equal((await c.req('/webshop/orders')).status,401);assert.equal((await signup(c)).status,200);assert.equal((await c.req('/data')).status,401);assert.equal((await c.req('/store/quote','POST',{}, {Origin:'https://evil.test'})).status,403);const r=await worker.fetch(new Request('https://shop.example/api/store/auth/register',{method:'POST',headers:{Origin:'https://shop.example','Content-Type':'application/json'},body:'{}'}),c.env);assert.equal(r.status,503);assert.equal((await c.req('/store/auth/me')).data.customer.email,'one@example.test');assert.match(c.cookie,/ws_customer/);await c.req('/store/auth/logout','POST',{});assert.equal((await c.req('/store/orders')).status,401)}finally{DB.close()}});
test('authoritative quote, immutable contract, idempotent order and stock once',async()=>{const DB=db();try{const c=client(DB);await signup(c);const q=await quote(c,2);assert.equal(q.data.total_cents,43900);assert.equal((await c.req('/store/orders','POST',{quote_id:q.data.id})).status,400);const o=await order(c,q.data.id);assert.equal(o.status,201);assert.equal((await order(c,q.data.id)).data.id,o.data.id);assert.equal(DB.prepare('SELECT stock FROM ws_catalog').first().stock,1);const doc=await c.req('/store/orders/'+o.data.id+'/document');assert.match(doc.data.text,/439.00 TL/);assert.throws(()=>DB.prepare("UPDATE ws_orders SET total_cents=1").run());await c.req('/store/orders/'+o.data.id+'/cancel','POST',{});await c.req('/store/orders/'+o.data.id+'/cancel','POST',{});assert.equal(DB.prepare('SELECT stock FROM ws_catalog').first().stock,3);assert.equal((await c.req('/store/orders/'+o.data.id+'/demo-payment','POST',{outcome:'success'})).status,409)}finally{DB.close()}});
test('stock race rolls back entire competing order, customer isolation and quote expiry',async()=>{const DB=db();try{const a=client(DB),b=client(DB);await signup(a);await signup(b,'two');const qa=await quote(a,3),qb=await quote(b,3);const oa=await order(a,qa.data.id);assert.equal((await order(b,qb.data.id)).status,409);assert.equal(DB.prepare('SELECT COUNT(*) n FROM ws_orders').first().n,1);assert.equal((await b.req('/store/orders/'+oa.data.id)).status,404);assert.equal((await b.req('/store/orders/'+oa.data.id+'/document')).status,404);assert.equal((await b.req('/store/requests','POST',{kind:'withdrawal',order_id:oa.data.id,message:'test'})).status,404);await a.req('/store/orders/'+oa.data.id+'/cancel','POST',{});const expired=await quote(b);DB.prepare('UPDATE ws_quotes SET expires_at=0 WHERE id=?').bind(expired.data.id).run();assert.equal((await order(b,expired.data.id)).status,409)}finally{DB.close()}});
test('demo payment and requests, password rotation revokes customer sessions',async()=>{const DB=db();try{const c=client(DB);await signup(c);const o=await order(c,(await quote(c)).data.id);await c.req('/store/orders/'+o.data.id+'/demo-payment','POST',{outcome:'success'});await c.req('/store/orders/'+o.data.id+'/demo-payment','POST',{outcome:'success'});assert.equal(DB.prepare('SELECT payment_status FROM ws_orders').first().payment_status,'demo_paid');assert.equal((await c.req('/store/requests','POST',{kind:'withdrawal',order_id:o.data.id,message:'Test cayma bildirimi'})).status,201);const saved=c.cookie;assert.equal((await c.req('/store/auth/password','POST',{current:'local-test-password-123',password:'new-local-password-123'})).status,200);assert.equal((await c.req('/store/orders','GET',null,{Cookie:saved})).status,401)}finally{DB.close()}});
test('Web Mağaza requires its own explicit staff permission',()=>{const legacy={ec_access:'write',lp_access:'none'};assert.throws(()=>permit(legacy,'/api/webshop/orders','GET'));const reader={...legacy,permissions:{ec:{webshop:'read'},lp:{}}};assert.doesNotThrow(()=>permit(reader,'/api/webshop/orders','GET'));assert.throws(()=>permit(reader,'/api/webshop/orders/a','POST'));assert.throws(()=>permit(reader,'/api/admin/users','GET'))});
test('admin workflow, hidden amounts and explicit staff access are enforced on actual responses',async()=>{const DB=db();try{const customer=client(DB);await signup(customer);const o=await order(customer,(await quote(customer)).data.id);const admin=client(DB);admin.env.SETUP_TOKEN='local-test-admin';assert.equal((await admin.req('/auth/setup','POST',{token:'local-test-admin',password:'local-admin-password-123'})).status,200);assert.equal((await admin.req('/webshop/orders/'+o.data.id,'POST',{status:'preparing'})).status,409);await customer.req('/store/orders/'+o.data.id+'/demo-payment','POST',{outcome:'success'});assert.equal((await admin.req('/webshop/orders/'+o.data.id,'POST',{status:'preparing'})).status,200);assert.equal((await admin.req('/webshop/orders/'+o.data.id,'POST',{status:'shipped'})).status,400);assert.equal((await admin.req('/webshop/orders/'+o.data.id,'POST',{status:'shipped',carrier:'Test Kargo',tracking:'TEST123'})).status,200);assert.equal((await admin.req('/webshop/orders/'+o.data.id,'POST',{status:'delivered'})).status,200);assert.equal((await admin.req('/webshop/overview')).data.delivered_cents,24900);assert.equal((await customer.req('/store/orders/'+o.data.id)).data.tracking,'TEST123');const permissions={ec:{webshop:'read',amounts:'none'},lp:{}};const invite=await admin.req('/admin/users','POST',{username:'webreader',name:'Web Reader',permissions});assert.equal(invite.status,200);const anon=client(DB);assert.equal((await anon.req('/auth/accept-invite','POST',{token:invite.data.invite_path.split("=")[1],password:'reader-password-12345'})).status,200);assert.equal((await anon.req('/auth/login','POST',{username:'webreader',password:'reader-password-12345'})).status,200);const detail=await anon.req('/webshop/orders/'+o.data.id);assert.equal(detail.status,200);assert.equal(detail.data.total_cents,null);assert.equal(detail.data.snapshot.items[0].price_cents,null);assert.equal(detail.data.snapshot.legal_text,undefined);assert.equal((await anon.req('/webshop/orders/'+o.data.id,'POST',{status:'cancelled'})).status,403);assert.equal((await anon.req('/webshop/customers')).status,200);assert.equal((await anon.req('/webshop/catalog/soil-standard','POST',{stock:99,price_cents:1,active:true})).status,403)}finally{DB.close()}});
test('abandoned payment releases inventory and fails the expired payment',async()=>{const DB=db();try{const c=client(DB);await signup(c);const o=await order(c,(await quote(c,3)).data.id);DB.prepare("UPDATE ws_orders SET created_at=datetime('now','-31 minutes') WHERE id=?").bind(o.data.id).run();assert.equal((await c.req('/store/orders/'+o.data.id+'/demo-payment','POST',{outcome:'success'})).status,409);assert.equal(DB.prepare('SELECT stock FROM ws_catalog').first().stock,3);assert.equal((await quote(c,3)).status,200)}finally{DB.close()}});

test('customer store pages are not served on the live accounting host',async()=>{
 const DB=db();try{
  // Dosyalar yayin paketinde bulunur ama canli adreste ACILMAZ.
  const assets={fetch:async()=>new Response('<html>magaza</html>',{headers:{'Content-Type':'text/html'}})};
  const live={DB,ASSETS:assets};
  for(const path of ['/magaza','/magaza/','/magaza/index.html','/magaza/yasal.html','/magaza/assets/hero.webp']){
   const r=await worker.fetch(new Request('https://muhasebe.lunapot.com'+path),live);
   assert.equal(r.status,404,path+' canli adreste sunulmamali');
  }
  // Yonetim modulu ve diger ekranlar etkilenmez.
  assert.equal((await worker.fetch(new Request('https://muhasebe.lunapot.com/webmagaza/'),live)).status,200);
  assert.equal((await worker.fetch(new Request('https://muhasebe.lunapot.com/uretim'),live)).status,200);
  // Yerel demo ortaminda magaza acilir.
  const demo={DB,ASSETS:assets,WS_MODE:'demo'};
  assert.equal((await worker.fetch(new Request('http://localhost/magaza/'),demo)).status,200);
  // Canli hostta WS_MODE tanimli olsa bile musteri magazasi kapali kalir.
  const yanlis={DB,ASSETS:assets,WS_MODE:'demo'};
  assert.equal((await worker.fetch(new Request('https://muhasebe.lunapot.com/magaza/'),yanlis)).status,404);
 }finally{DB.close()}
});

test('customer store writes stay closed on the live host',async()=>{
 const DB=db();try{
  const live={DB};
  for(const [path,method] of [['/api/store/auth/register','POST'],['/api/store/quote','POST'],['/api/store/orders','POST']]){
   const r=await worker.fetch(new Request('https://muhasebe.lunapot.com'+path,{method,headers:{Origin:'https://muhasebe.lunapot.com','Content-Type':'application/json'},body:'{}'}),live);
   assert.equal(r.status,503,path+' canlida yazmaya kapali olmali');
  }
  const config=await worker.fetch(new Request('https://muhasebe.lunapot.com/api/store/config'),live);
  const data=await config.json();
  assert.equal(data.mode,'closed');
  assert.equal(data.live_ready,false);
  assert.ok(data.blockers.length,'satisa hazirlik eksikleri gizlenmemeli');
 }finally{DB.close()}
});
