-- Invoice recognition and physical receipt are separate, append-only operations.
CREATE TABLE workspace_settings(workspace TEXT PRIMARY KEY CHECK(workspace IN ('ec','lp')),legal_name TEXT NOT NULL DEFAULT '',tax_id TEXT NOT NULL DEFAULT '',updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
INSERT INTO workspace_settings(workspace) VALUES('ec'),('lp');
CREATE TABLE document_registry(document_key TEXT PRIMARY KEY,workspace TEXT NOT NULL CHECK(workspace IN ('ec','lp')),invoice_id TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);

ALTER TABLE ec_purchase_invoices ADD COLUMN receiver_tax_id TEXT NOT NULL DEFAULT '';
ALTER TABLE ec_purchase_lines ADD COLUMN line_type TEXT NOT NULL DEFAULT 'product' CHECK(line_type IN ('product','expense'));
ALTER TABLE ec_purchase_lines ADD COLUMN expense_category TEXT NOT NULL DEFAULT 'other' CHECK(expense_category IN ('shipping','commission','advertising','rent','packaging','other'));
ALTER TABLE ec_purchase_lines ADD COLUMN expense_treatment TEXT CHECK(expense_treatment IN ('general','sales_fee'));
CREATE TABLE ec_goods_receipts(id TEXT PRIMARY KEY,line_id TEXT NOT NULL REFERENCES ec_purchase_lines(id),quantity_milli INTEGER NOT NULL CHECK(quantity_milli>0),value_cents INTEGER NOT NULL CHECK(value_cents>=0),occurred_on TEXT NOT NULL,reference TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(line_id,reference));
CREATE INDEX ec_receipts_line ON ec_goods_receipts(line_id);
-- Preserve stock receipts already generated by version 1.
INSERT INTO ec_goods_receipts(id,line_id,quantity_milli,value_cents,occurred_on,reference)
SELECT 'legacy-'||l.id,l.id,l.quantity_milli,l.net_cents,i.invoice_date,'legacy-'||i.id FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE i.status='posted' AND EXISTS(SELECT 1 FROM ec_stock_movements m WHERE m.id=l.id);
INSERT OR IGNORE INTO document_registry(document_key,workspace,invoice_id) SELECT 'uuid:'||lower(uuid),'ec',id FROM ec_purchase_invoices WHERE uuid IS NOT NULL AND uuid!='';
INSERT OR IGNORE INTO document_registry(document_key,workspace,invoice_id) SELECT CASE WHEN s.tax_id IS NOT NULL AND s.tax_id!='' THEN 'invoice:'||s.tax_id||':' ELSE 'manual:ec:'||s.id||':' END||upper(replace(replace(replace(replace(i.invoice_no,' ',''),char(9),''),char(10),''),char(13),'')),'ec',i.id FROM ec_purchase_invoices i JOIN ec_suppliers s ON s.id=i.supplier_id;
DROP TRIGGER ec_invoice_stock;
DROP TRIGGER ec_invoice_validate;
CREATE TRIGGER ec_invoice_validate BEFORE UPDATE OF status ON ec_purchase_invoices WHEN NEW.status='posted' BEGIN
 SELECT CASE WHEN OLD.status!='draft' THEN RAISE(ABORT,'INVOICE_ALREADY_HANDLED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM ec_purchase_lines WHERE invoice_id=NEW.id AND line_type='expense' AND expense_treatment IS NULL) THEN RAISE(ABORT,'UNCLASSIFIED_FEE') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_purchase_lines WHERE invoice_id=NEW.id) OR EXISTS(SELECT 1 FROM ec_purchase_lines WHERE invoice_id=NEW.id AND line_type='product' AND (product_id IS NULL OR quantity_milli IS NULL)) THEN RAISE(ABORT,'UNMAPPED_INVOICE') END;
END;
CREATE TRIGGER ec_invoice_expenses AFTER UPDATE OF status ON ec_purchase_invoices WHEN NEW.status='posted' BEGIN
 INSERT INTO ec_expenses(id,reference,category,amount_cents,occurred_on,paid,notes) SELECT 'invoice-'||id,'invoice-'||id,expense_category,net_cents,NEW.invoice_date,0,description FROM ec_purchase_lines WHERE invoice_id=NEW.id AND line_type='expense' AND expense_treatment='general';
END;
CREATE TRIGGER ec_receipt_validate BEFORE INSERT ON ec_goods_receipts BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.line_id AND l.line_type='product' AND i.status='posted') THEN RAISE(ABORT,'RECEIPT_NOT_POSTED') END;
 SELECT CASE WHEN NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM ec_goods_receipts WHERE line_id=NEW.line_id),0)>(SELECT quantity_milli FROM ec_purchase_lines WHERE id=NEW.line_id) THEN RAISE(ABORT,'RECEIPT_EXCEEDS_INVOICE') END;
 SELECT CASE WHEN NEW.value_cents != (SELECT CAST(ROUND(net_cents*(NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM ec_goods_receipts WHERE line_id=NEW.line_id),0))/(quantity_milli*1.0)) AS INTEGER)-COALESCE((SELECT SUM(value_cents) FROM ec_goods_receipts WHERE line_id=NEW.line_id),0) FROM ec_purchase_lines WHERE id=NEW.line_id) THEN RAISE(ABORT,'RECEIPT_COST_MISMATCH') END;
END;
CREATE TRIGGER ec_receipt_stock AFTER INSERT ON ec_goods_receipts BEGIN
 INSERT INTO ec_stock_movements(id,product_id,quantity_milli,value_cents,kind,reference,notes,occurred_on) SELECT NEW.id,product_id,NEW.quantity_milli,NEW.value_cents,'purchase',NEW.id,NEW.reference,NEW.occurred_on FROM ec_purchase_lines WHERE id=NEW.line_id;
END;
CREATE TRIGGER ec_receipt_no_update BEFORE UPDATE ON ec_goods_receipts BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER ec_receipt_no_delete BEFORE DELETE ON ec_goods_receipts BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER ec_invoice_line_no_delete BEFORE DELETE ON ec_purchase_lines WHEN (SELECT status FROM ec_purchase_invoices WHERE id=OLD.invoice_id)!='draft' BEGIN SELECT RAISE(ABORT,'IMMUTABLE_INVOICE'); END;
CREATE TRIGGER ec_invoice_line_no_insert BEFORE INSERT ON ec_purchase_lines WHEN (SELECT status FROM ec_purchase_invoices WHERE id=NEW.invoice_id)!='draft' BEGIN SELECT RAISE(ABORT,'IMMUTABLE_INVOICE'); END;

ALTER TABLE lp_purchase_invoices ADD COLUMN receiver_tax_id TEXT NOT NULL DEFAULT '';
ALTER TABLE lp_purchase_lines ADD COLUMN line_type TEXT NOT NULL DEFAULT 'product' CHECK(line_type IN ('product','expense'));
ALTER TABLE lp_purchase_lines ADD COLUMN expense_category TEXT NOT NULL DEFAULT 'other' CHECK(expense_category IN ('shipping','commission','advertising','rent','packaging','other'));
ALTER TABLE lp_purchase_lines ADD COLUMN expense_treatment TEXT CHECK(expense_treatment IN ('general','sales_fee'));
CREATE TABLE lp_goods_receipts(id TEXT PRIMARY KEY,line_id TEXT NOT NULL REFERENCES lp_purchase_lines(id),quantity_milli INTEGER NOT NULL CHECK(quantity_milli>0),value_cents INTEGER NOT NULL CHECK(value_cents>=0),occurred_on TEXT NOT NULL,reference TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(line_id,reference));
CREATE INDEX lp_receipts_line ON lp_goods_receipts(line_id);
-- Preserve stock receipts already generated by version 1.
INSERT INTO lp_goods_receipts(id,line_id,quantity_milli,value_cents,occurred_on,reference)
SELECT 'legacy-'||l.id,l.id,l.quantity_milli,l.net_cents,i.invoice_date,'legacy-'||i.id FROM lp_purchase_lines l JOIN lp_purchase_invoices i ON i.id=l.invoice_id WHERE i.status='posted' AND EXISTS(SELECT 1 FROM lp_stock_movements m WHERE m.id=l.id);
INSERT OR IGNORE INTO document_registry(document_key,workspace,invoice_id) SELECT 'uuid:'||lower(uuid),'lp',id FROM lp_purchase_invoices WHERE uuid IS NOT NULL AND uuid!='';
INSERT OR IGNORE INTO document_registry(document_key,workspace,invoice_id) SELECT CASE WHEN s.tax_id IS NOT NULL AND s.tax_id!='' THEN 'invoice:'||s.tax_id||':' ELSE 'manual:lp:'||s.id||':' END||upper(replace(replace(replace(replace(i.invoice_no,' ',''),char(9),''),char(10),''),char(13),'')),'lp',i.id FROM lp_purchase_invoices i JOIN lp_suppliers s ON s.id=i.supplier_id;
DROP TRIGGER lp_invoice_stock;
DROP TRIGGER lp_invoice_validate;
CREATE TRIGGER lp_invoice_validate BEFORE UPDATE OF status ON lp_purchase_invoices WHEN NEW.status='posted' BEGIN
 SELECT CASE WHEN OLD.status!='draft' THEN RAISE(ABORT,'INVOICE_ALREADY_HANDLED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM lp_purchase_lines WHERE invoice_id=NEW.id AND line_type='expense' AND expense_treatment IS NULL) THEN RAISE(ABORT,'UNCLASSIFIED_FEE') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM lp_purchase_lines WHERE invoice_id=NEW.id) OR EXISTS(SELECT 1 FROM lp_purchase_lines WHERE invoice_id=NEW.id AND line_type='product' AND (product_id IS NULL OR quantity_milli IS NULL)) THEN RAISE(ABORT,'UNMAPPED_INVOICE') END;
END;
CREATE TRIGGER lp_invoice_expenses AFTER UPDATE OF status ON lp_purchase_invoices WHEN NEW.status='posted' BEGIN
 INSERT INTO lp_expenses(id,reference,category,amount_cents,occurred_on,paid,notes) SELECT 'invoice-'||id,'invoice-'||id,expense_category,net_cents,NEW.invoice_date,0,description FROM lp_purchase_lines WHERE invoice_id=NEW.id AND line_type='expense' AND expense_treatment='general';
END;
CREATE TRIGGER lp_receipt_validate BEFORE INSERT ON lp_goods_receipts BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM lp_purchase_lines l JOIN lp_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.line_id AND l.line_type='product' AND i.status='posted') THEN RAISE(ABORT,'RECEIPT_NOT_POSTED') END;
 SELECT CASE WHEN NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM lp_goods_receipts WHERE line_id=NEW.line_id),0)>(SELECT quantity_milli FROM lp_purchase_lines WHERE id=NEW.line_id) THEN RAISE(ABORT,'RECEIPT_EXCEEDS_INVOICE') END;
 SELECT CASE WHEN NEW.value_cents != (SELECT CAST(ROUND(net_cents*(NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM lp_goods_receipts WHERE line_id=NEW.line_id),0))/(quantity_milli*1.0)) AS INTEGER)-COALESCE((SELECT SUM(value_cents) FROM lp_goods_receipts WHERE line_id=NEW.line_id),0) FROM lp_purchase_lines WHERE id=NEW.line_id) THEN RAISE(ABORT,'RECEIPT_COST_MISMATCH') END;
END;
CREATE TRIGGER lp_receipt_stock AFTER INSERT ON lp_goods_receipts BEGIN
 INSERT INTO lp_stock_movements(id,product_id,quantity_milli,value_cents,kind,reference,notes,occurred_on) SELECT NEW.id,product_id,NEW.quantity_milli,NEW.value_cents,'purchase',NEW.id,NEW.reference,NEW.occurred_on FROM lp_purchase_lines WHERE id=NEW.line_id;
END;
CREATE TRIGGER lp_receipt_no_update BEFORE UPDATE ON lp_goods_receipts BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER lp_receipt_no_delete BEFORE DELETE ON lp_goods_receipts BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER lp_invoice_line_no_delete BEFORE DELETE ON lp_purchase_lines WHEN (SELECT status FROM lp_purchase_invoices WHERE id=OLD.invoice_id)!='draft' BEGIN SELECT RAISE(ABORT,'IMMUTABLE_INVOICE'); END;
CREATE TRIGGER lp_invoice_line_no_insert BEFORE INSERT ON lp_purchase_lines WHEN (SELECT status FROM lp_purchase_invoices WHERE id=NEW.invoice_id)!='draft' BEGIN SELECT RAISE(ABORT,'IMMUTABLE_INVOICE'); END;
