-- E-commerce only. Reserving never changes physical stock; shipping consumes once.
CREATE TABLE ec_order_packages(id TEXT PRIMARY KEY,channel TEXT NOT NULL CHECK(channel IN ('trendyol','hepsiburada','other')),external_id TEXT NOT NULL,order_no TEXT NOT NULL DEFAULT '',occurred_on TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','reserved','shipped','delivered','cancelled')),external_status TEXT NOT NULL DEFAULT '',source_fingerprint TEXT NOT NULL,source_changed INTEGER NOT NULL DEFAULT 0 CHECK(source_changed IN (0,1)),shipment_reference TEXT UNIQUE,shipped_on TEXT,delivered_on TEXT,cancel_reason TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(channel,external_id));
CREATE TABLE ec_order_lines(id TEXT PRIMARY KEY,package_id TEXT NOT NULL REFERENCES ec_order_packages(id),external_id TEXT NOT NULL,sku TEXT NOT NULL DEFAULT '',name TEXT NOT NULL,product_id TEXT REFERENCES ec_products(id),quantity_milli INTEGER NOT NULL CHECK(typeof(quantity_milli)='integer' AND quantity_milli>0),gross_cents INTEGER CHECK(gross_cents IS NULL OR (typeof(gross_cents)='integer' AND gross_cents>=0)),vat_bps INTEGER CHECK(vat_bps IS NULL OR (typeof(vat_bps)='integer' AND vat_bps BETWEEN 0 AND 10000)),net_revenue_cents INTEGER CHECK(net_revenue_cents IS NULL OR (typeof(net_revenue_cents)='integer' AND net_revenue_cents>=0)),sale_id TEXT UNIQUE REFERENCES ec_sale_entries(id),UNIQUE(package_id,external_id));
CREATE INDEX ec_order_lines_package ON ec_order_lines(package_id);
CREATE TABLE ec_order_reservations(id TEXT PRIMARY KEY,package_id TEXT NOT NULL REFERENCES ec_order_packages(id),line_id TEXT NOT NULL UNIQUE REFERENCES ec_order_lines(id),product_id TEXT NOT NULL REFERENCES ec_products(id),quantity_milli INTEGER NOT NULL CHECK(quantity_milli>0),released_on TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ec_order_reservation_product ON ec_order_reservations(product_id,released_on);
CREATE TRIGGER ec_order_line_lock BEFORE UPDATE ON ec_order_lines WHEN (SELECT status FROM ec_order_packages WHERE id=OLD.package_id)!='draft' AND (NEW.product_id IS NOT OLD.product_id OR NEW.quantity_milli!=OLD.quantity_milli OR NEW.gross_cents IS NOT OLD.gross_cents OR NEW.vat_bps IS NOT OLD.vat_bps OR NEW.net_revenue_cents IS NOT OLD.net_revenue_cents OR NEW.package_id!=OLD.package_id OR NEW.external_id!=OLD.external_id OR NEW.sku!=OLD.sku OR NEW.name!=OLD.name OR OLD.sale_id IS NOT NULL) BEGIN SELECT RAISE(ABORT,'ORDER_LOCKED'); END;
CREATE TRIGGER ec_order_line_insert_lock BEFORE INSERT ON ec_order_lines WHEN (SELECT status FROM ec_order_packages WHERE id=NEW.package_id)!='draft' BEGIN SELECT RAISE(ABORT,'ORDER_LOCKED'); END;
CREATE TRIGGER ec_order_line_delete_lock BEFORE DELETE ON ec_order_lines BEGIN SELECT RAISE(ABORT,'ORDER_LOCKED'); END;
CREATE TRIGGER ec_order_transition BEFORE UPDATE OF status ON ec_order_packages WHEN NEW.status!=OLD.status BEGIN
 SELECT CASE WHEN NOT ((OLD.status='draft' AND NEW.status IN ('reserved','cancelled')) OR (OLD.status='reserved' AND NEW.status IN ('shipped','cancelled')) OR (OLD.status='shipped' AND NEW.status='delivered')) THEN RAISE(ABORT,'INVALID_ORDER_TRANSITION') END;
 SELECT CASE WHEN NEW.status IN ('reserved','shipped') AND NEW.source_changed=1 THEN RAISE(ABORT,'ORDER_SOURCE_CHANGED') END;
END;
CREATE TRIGGER ec_order_reserve_validate BEFORE UPDATE OF status ON ec_order_packages WHEN NEW.status='reserved' AND OLD.status!='reserved' BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_order_lines WHERE package_id=NEW.id) OR EXISTS(SELECT 1 FROM ec_order_lines WHERE package_id=NEW.id AND product_id IS NULL) THEN RAISE(ABORT,'ORDER_UNMAPPED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM ec_order_lines WHERE package_id=NEW.id AND net_revenue_cents IS NULL) THEN RAISE(ABORT,'ORDER_MISSING_AMOUNT') END;
 SELECT CASE WHEN EXISTS(SELECT l.product_id FROM ec_order_lines l JOIN ec_stock_balances b ON b.product_id=l.product_id WHERE l.package_id=NEW.id GROUP BY l.product_id HAVING SUM(l.quantity_milli)+COALESCE((SELECT SUM(r.quantity_milli) FROM ec_order_reservations r WHERE r.product_id=l.product_id AND r.released_on IS NULL),0)>b.quantity_milli) THEN RAISE(ABORT,'ORDER_INSUFFICIENT_STOCK') END;
END;
CREATE TRIGGER ec_order_reserve_apply AFTER UPDATE OF status ON ec_order_packages WHEN NEW.status='reserved' AND OLD.status!='reserved' BEGIN
 INSERT INTO ec_order_reservations(id,package_id,line_id,product_id,quantity_milli) SELECT id,NEW.id,id,product_id,quantity_milli FROM ec_order_lines WHERE package_id=NEW.id;
END;
CREATE TRIGGER ec_order_release AFTER UPDATE OF status ON ec_order_packages WHEN NEW.status IN ('shipped','cancelled') AND OLD.status='reserved' BEGIN UPDATE ec_order_reservations SET released_on=CURRENT_TIMESTAMP WHERE package_id=NEW.id AND released_on IS NULL; END;
CREATE TRIGGER ec_stock_reservations_guard BEFORE INSERT ON ec_stock_movements WHEN NEW.quantity_milli<0 BEGIN
 SELECT CASE WHEN (SELECT quantity_milli FROM ec_stock_balances WHERE product_id=NEW.product_id)+NEW.quantity_milli<COALESCE((SELECT SUM(quantity_milli) FROM ec_order_reservations WHERE product_id=NEW.product_id AND released_on IS NULL),0) THEN RAISE(ABORT,'STOCK_RESERVED') END;
END;
