-- Source inbox only: these records never directly post finance, stock or payments.
CREATE TABLE ec_provider_connections(provider TEXT PRIMARY KEY CHECK(provider IN('trendyol','hepsiburada','edm')),seller_id TEXT NOT NULL,encrypted_credentials TEXT NOT NULL,configured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_success_at TEXT,last_error TEXT);
CREATE TABLE ec_provider_records(id TEXT PRIMARY KEY,provider TEXT NOT NULL,seller_id TEXT NOT NULL,kind TEXT NOT NULL,external_id TEXT NOT NULL,fingerprint TEXT NOT NULL,payload_json TEXT NOT NULL,source_updated_at TEXT,first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(provider,seller_id,kind,external_id,fingerprint));
CREATE INDEX ec_provider_record_lookup ON ec_provider_records(provider,seller_id,kind,external_id,source_updated_at,last_seen_at);
CREATE TABLE ec_provider_cursors(provider TEXT NOT NULL,seller_id TEXT NOT NULL,kind TEXT NOT NULL,query_key TEXT NOT NULL,query_json TEXT NOT NULL,next_page INTEGER NOT NULL,has_more INTEGER NOT NULL CHECK(has_more IN(0,1)),last_success_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(provider,seller_id,kind,query_key));
CREATE TABLE lp_provider_connections(provider TEXT PRIMARY KEY CHECK(provider IN('trendyol','hepsiburada','edm')),seller_id TEXT NOT NULL,encrypted_credentials TEXT NOT NULL,configured_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_success_at TEXT,last_error TEXT);
CREATE TABLE lp_provider_records(id TEXT PRIMARY KEY,provider TEXT NOT NULL,seller_id TEXT NOT NULL,kind TEXT NOT NULL,external_id TEXT NOT NULL,fingerprint TEXT NOT NULL,payload_json TEXT NOT NULL,source_updated_at TEXT,first_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,last_seen_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(provider,seller_id,kind,external_id,fingerprint));
CREATE INDEX lp_provider_record_lookup ON lp_provider_records(provider,seller_id,kind,external_id,source_updated_at,last_seen_at);
CREATE TABLE lp_provider_cursors(provider TEXT NOT NULL,seller_id TEXT NOT NULL,kind TEXT NOT NULL,query_key TEXT NOT NULL,query_json TEXT NOT NULL,next_page INTEGER NOT NULL,has_more INTEGER NOT NULL CHECK(has_more IN(0,1)),last_success_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(provider,seller_id,kind,query_key));
