-- Reviewed invoice-to-sale allocations. Invoice net amounts only; no cash or duplicate general expense.

CREATE TABLE ec_fee_allocations(id TEXT PRIMARY KEY,invoice_line_id TEXT NOT NULL REFERENCES ec_purchase_lines(id),sale_id TEXT NOT NULL REFERENCES ec_sale_entries(id),component TEXT NOT NULL CHECK(component IN ('shipping','commission','other')),amount_cents INTEGER NOT NULL CHECK(typeof(amount_cents)='integer' AND amount_cents>0),takeover INTEGER NOT NULL DEFAULT 0 CHECK(takeover IN (0,1)),reference TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at TEXT,reversal_reason TEXT);
CREATE UNIQUE INDEX ec_fee_allocation_active ON ec_fee_allocations(invoice_line_id,sale_id) WHERE reversed_at IS NULL;
CREATE INDEX ec_fee_allocation_sale ON ec_fee_allocations(sale_id,component,reversed_at);
CREATE TRIGGER ec_fee_allocation_validate BEFORE INSERT ON ec_fee_allocations BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.invoice_line_id AND i.status='posted' AND l.line_type='expense' AND l.expense_treatment='sales_fee' AND NEW.component= CASE WHEN l.expense_category IN ('shipping','commission') THEN l.expense_category ELSE 'other' END ) THEN RAISE(ABORT,'INVALID_FEE_SOURCE') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_sale_entries WHERE id=NEW.sale_id AND kind='sale') THEN RAISE(ABORT,'INVALID_FEE_SALE') END;
 SELECT CASE WHEN NEW.amount_cents+COALESCE((SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE invoice_line_id=NEW.invoice_line_id AND reversed_at IS NULL),0)>(SELECT net_cents FROM ec_purchase_lines WHERE id=NEW.invoice_line_id) THEN RAISE(ABORT,'FEE_OVERALLOCATION') END;
 SELECT CASE WHEN NEW.takeover=0 AND NOT EXISTS(SELECT 1 FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component=NEW.component AND reversed_at IS NULL) AND (SELECT CASE NEW.component WHEN 'shipping' THEN shipping_cents WHEN 'commission' THEN commission_cents ELSE other_cents END FROM ec_sale_entries WHERE id=NEW.sale_id) IS NOT NULL THEN RAISE(ABORT,'FEE_TAKEOVER_REQUIRED') END;
 SELECT CASE WHEN NEW.reversed_at IS NOT NULL THEN RAISE(ABORT,'INVALID_FEE_ALLOCATION') END;
END;
CREATE TRIGGER ec_sale_linked_fees_lock BEFORE UPDATE OF shipping_cents,commission_cents,other_cents ON ec_sale_entries BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='shipping' AND reversed_at IS NULL) AND NEW.shipping_cents IS NOT (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='shipping' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='commission' AND reversed_at IS NULL) AND NEW.commission_cents IS NOT (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='commission' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='other' AND reversed_at IS NULL) AND NEW.other_cents IS NOT (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=OLD.id AND component='other' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
END;
CREATE TRIGGER ec_fee_allocation_apply AFTER INSERT ON ec_fee_allocations BEGIN
 INSERT INTO ec_fee_audit(id,sale_id,old_values,new_values) SELECT 'allocation:'||NEW.id,NEW.sale_id,json_object('shipping',shipping_cents,'commission',commission_cents,'other',other_cents,'status',fees_status),json_object('allocation_id',NEW.id,'source_line_id',NEW.invoice_line_id,'component',NEW.component,'amount_cents',NEW.amount_cents,'takeover',NEW.takeover) FROM ec_sale_entries WHERE id=NEW.sale_id;
 UPDATE ec_sale_entries SET
 shipping_cents= CASE WHEN NEW.component='shipping' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='shipping' AND reversed_at IS NULL) ELSE shipping_cents END ,
 commission_cents= CASE WHEN NEW.component='commission' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='commission' AND reversed_at IS NULL) ELSE commission_cents END ,
 other_cents= CASE WHEN NEW.component='other' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='other' AND reversed_at IS NULL) ELSE other_cents END ,
 fees_status= CASE WHEN fees_status='confirmed' AND (NEW.component='shipping' OR shipping_cents IS NOT NULL) AND (NEW.component='commission' OR commission_cents IS NOT NULL) AND (NEW.component='other' OR other_cents IS NOT NULL) THEN 'confirmed' WHEN (SELECT COUNT(DISTINCT component) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND reversed_at IS NULL)=3 THEN 'confirmed' ELSE 'pending' END WHERE id=NEW.sale_id;
END;
CREATE TRIGGER ec_fee_allocation_reverse_validate BEFORE UPDATE ON ec_fee_allocations BEGIN
 SELECT CASE WHEN OLD.reversed_at IS NOT NULL OR NEW.reversed_at IS NULL OR length(trim(COALESCE(NEW.reversal_reason,'')))=0 OR NEW.id!=OLD.id OR NEW.invoice_line_id!=OLD.invoice_line_id OR NEW.sale_id!=OLD.sale_id OR NEW.component!=OLD.component OR NEW.amount_cents!=OLD.amount_cents OR NEW.reference!=OLD.reference OR NEW.takeover!=OLD.takeover OR NEW.created_at!=OLD.created_at THEN RAISE(ABORT,'IMMUTABLE_FEE_ALLOCATION') END;
END;
CREATE TRIGGER ec_fee_allocation_reverse AFTER UPDATE ON ec_fee_allocations BEGIN
 INSERT INTO ec_fee_audit(id,sale_id,old_values,new_values) SELECT 'allocation-reverse:'||NEW.id,NEW.sale_id,json_object('shipping',shipping_cents,'commission',commission_cents,'other',other_cents,'status',fees_status),json_object('reversed_allocation_id',NEW.id,'reason',NEW.reversal_reason) FROM ec_sale_entries WHERE id=NEW.sale_id;
 UPDATE ec_sale_entries SET shipping_cents= CASE WHEN NEW.component='shipping' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='shipping' AND reversed_at IS NULL) ELSE shipping_cents END ,commission_cents= CASE WHEN NEW.component='commission' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='commission' AND reversed_at IS NULL) ELSE commission_cents END ,other_cents= CASE WHEN NEW.component='other' THEN (SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component='other' AND reversed_at IS NULL) ELSE other_cents END ,fees_status='pending' WHERE id=NEW.sale_id;
END;
CREATE TRIGGER ec_fee_allocation_no_delete BEFORE DELETE ON ec_fee_allocations BEGIN SELECT RAISE(ABORT,'IMMUTABLE_FEE_ALLOCATION'); END;

CREATE TABLE lp_fee_allocations(id TEXT PRIMARY KEY,invoice_line_id TEXT NOT NULL REFERENCES lp_purchase_lines(id),sale_id TEXT NOT NULL REFERENCES lp_sale_entries(id),component TEXT NOT NULL CHECK(component IN ('shipping','commission','other')),amount_cents INTEGER NOT NULL CHECK(typeof(amount_cents)='integer' AND amount_cents>0),takeover INTEGER NOT NULL DEFAULT 0 CHECK(takeover IN (0,1)),reference TEXT NOT NULL UNIQUE,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,reversed_at TEXT,reversal_reason TEXT);
CREATE UNIQUE INDEX lp_fee_allocation_active ON lp_fee_allocations(invoice_line_id,sale_id) WHERE reversed_at IS NULL;
CREATE INDEX lp_fee_allocation_sale ON lp_fee_allocations(sale_id,component,reversed_at);
CREATE TRIGGER lp_fee_allocation_validate BEFORE INSERT ON lp_fee_allocations BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM lp_purchase_lines l JOIN lp_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.invoice_line_id AND i.status='posted' AND l.line_type='expense' AND l.expense_treatment='sales_fee' AND NEW.component= CASE WHEN l.expense_category IN ('shipping','commission') THEN l.expense_category ELSE 'other' END ) THEN RAISE(ABORT,'INVALID_FEE_SOURCE') END;
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM lp_sale_entries WHERE id=NEW.sale_id AND kind='sale') THEN RAISE(ABORT,'INVALID_FEE_SALE') END;
 SELECT CASE WHEN NEW.amount_cents+COALESCE((SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE invoice_line_id=NEW.invoice_line_id AND reversed_at IS NULL),0)>(SELECT net_cents FROM lp_purchase_lines WHERE id=NEW.invoice_line_id) THEN RAISE(ABORT,'FEE_OVERALLOCATION') END;
 SELECT CASE WHEN NEW.takeover=0 AND NOT EXISTS(SELECT 1 FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component=NEW.component AND reversed_at IS NULL) AND (SELECT CASE NEW.component WHEN 'shipping' THEN shipping_cents WHEN 'commission' THEN commission_cents ELSE other_cents END FROM lp_sale_entries WHERE id=NEW.sale_id) IS NOT NULL THEN RAISE(ABORT,'FEE_TAKEOVER_REQUIRED') END;
 SELECT CASE WHEN NEW.reversed_at IS NOT NULL THEN RAISE(ABORT,'INVALID_FEE_ALLOCATION') END;
END;
CREATE TRIGGER lp_sale_linked_fees_lock BEFORE UPDATE OF shipping_cents,commission_cents,other_cents ON lp_sale_entries BEGIN
 SELECT CASE WHEN EXISTS(SELECT 1 FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='shipping' AND reversed_at IS NULL) AND NEW.shipping_cents IS NOT (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='shipping' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='commission' AND reversed_at IS NULL) AND NEW.commission_cents IS NOT (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='commission' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='other' AND reversed_at IS NULL) AND NEW.other_cents IS NOT (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=OLD.id AND component='other' AND reversed_at IS NULL) THEN RAISE(ABORT,'RECONCILED_FEE_LOCKED') END;
END;
CREATE TRIGGER lp_fee_allocation_apply AFTER INSERT ON lp_fee_allocations BEGIN
 INSERT INTO lp_fee_audit(id,sale_id,old_values,new_values) SELECT 'allocation:'||NEW.id,NEW.sale_id,json_object('shipping',shipping_cents,'commission',commission_cents,'other',other_cents,'status',fees_status),json_object('allocation_id',NEW.id,'source_line_id',NEW.invoice_line_id,'component',NEW.component,'amount_cents',NEW.amount_cents,'takeover',NEW.takeover) FROM lp_sale_entries WHERE id=NEW.sale_id;
 UPDATE lp_sale_entries SET
 shipping_cents= CASE WHEN NEW.component='shipping' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='shipping' AND reversed_at IS NULL) ELSE shipping_cents END ,
 commission_cents= CASE WHEN NEW.component='commission' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='commission' AND reversed_at IS NULL) ELSE commission_cents END ,
 other_cents= CASE WHEN NEW.component='other' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='other' AND reversed_at IS NULL) ELSE other_cents END ,
 fees_status= CASE WHEN fees_status='confirmed' AND (NEW.component='shipping' OR shipping_cents IS NOT NULL) AND (NEW.component='commission' OR commission_cents IS NOT NULL) AND (NEW.component='other' OR other_cents IS NOT NULL) THEN 'confirmed' WHEN (SELECT COUNT(DISTINCT component) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND reversed_at IS NULL)=3 THEN 'confirmed' ELSE 'pending' END WHERE id=NEW.sale_id;
END;
CREATE TRIGGER lp_fee_allocation_reverse_validate BEFORE UPDATE ON lp_fee_allocations BEGIN
 SELECT CASE WHEN OLD.reversed_at IS NOT NULL OR NEW.reversed_at IS NULL OR length(trim(COALESCE(NEW.reversal_reason,'')))=0 OR NEW.id!=OLD.id OR NEW.invoice_line_id!=OLD.invoice_line_id OR NEW.sale_id!=OLD.sale_id OR NEW.component!=OLD.component OR NEW.amount_cents!=OLD.amount_cents OR NEW.reference!=OLD.reference OR NEW.takeover!=OLD.takeover OR NEW.created_at!=OLD.created_at THEN RAISE(ABORT,'IMMUTABLE_FEE_ALLOCATION') END;
END;
CREATE TRIGGER lp_fee_allocation_reverse AFTER UPDATE ON lp_fee_allocations BEGIN
 INSERT INTO lp_fee_audit(id,sale_id,old_values,new_values) SELECT 'allocation-reverse:'||NEW.id,NEW.sale_id,json_object('shipping',shipping_cents,'commission',commission_cents,'other',other_cents,'status',fees_status),json_object('reversed_allocation_id',NEW.id,'reason',NEW.reversal_reason) FROM lp_sale_entries WHERE id=NEW.sale_id;
 UPDATE lp_sale_entries SET shipping_cents= CASE WHEN NEW.component='shipping' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='shipping' AND reversed_at IS NULL) ELSE shipping_cents END ,commission_cents= CASE WHEN NEW.component='commission' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='commission' AND reversed_at IS NULL) ELSE commission_cents END ,other_cents= CASE WHEN NEW.component='other' THEN (SELECT SUM(amount_cents) FROM lp_fee_allocations WHERE sale_id=NEW.sale_id AND component='other' AND reversed_at IS NULL) ELSE other_cents END ,fees_status='pending' WHERE id=NEW.sale_id;
END;
CREATE TRIGGER lp_fee_allocation_no_delete BEFORE DELETE ON lp_fee_allocations BEGIN SELECT RAISE(ABORT,'IMMUTABLE_FEE_ALLOCATION'); END;
