-- Reviewed refresh preserves both prior local state and the immutable provider revision.
CREATE TABLE ec_order_refresh_audit(id TEXT PRIMARY KEY,package_id TEXT NOT NULL REFERENCES ec_order_packages(id),source_record_id TEXT NOT NULL REFERENCES ec_provider_records(id),old_package_json TEXT NOT NULL,old_lines_json TEXT NOT NULL,new_fingerprint TEXT NOT NULL,applied INTEGER NOT NULL DEFAULT 0 CHECK(applied IN (0,1)),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(package_id,source_record_id));
CREATE TRIGGER ec_order_refresh_validate BEFORE INSERT ON ec_order_refresh_audit BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_order_packages p JOIN ec_provider_records r ON r.id=NEW.source_record_id AND r.external_id=p.external_id AND r.provider=p.channel AND r.kind='orders' WHERE p.id=NEW.package_id AND p.status='draft') OR EXISTS(SELECT 1 FROM ec_order_reservations WHERE package_id=NEW.package_id) OR EXISTS(SELECT 1 FROM ec_order_lines WHERE package_id=NEW.package_id AND sale_id IS NOT NULL) THEN RAISE(ABORT,'ORDER_REFRESH_BLOCKED') END;
 SELECT CASE WHEN NEW.source_record_id IS NOT (SELECT r.id FROM ec_provider_records r JOIN ec_provider_connections c ON c.provider=r.provider AND c.seller_id=r.seller_id JOIN ec_order_packages p ON p.external_id=r.external_id AND p.channel=r.provider WHERE p.id=NEW.package_id AND r.kind='orders' ORDER BY r.source_updated_at DESC,r.last_seen_at DESC,r.rowid DESC LIMIT 1) THEN RAISE(ABORT,'ORDER_REFRESH_BLOCKED') END;
END;
DROP TRIGGER ec_order_line_delete_lock;
CREATE TRIGGER ec_order_line_delete_lock BEFORE DELETE ON ec_order_lines WHEN (SELECT status FROM ec_order_packages WHERE id=OLD.package_id)!='draft' OR NOT EXISTS(SELECT 1 FROM ec_order_refresh_audit WHERE package_id=OLD.package_id AND applied=0) BEGIN SELECT RAISE(ABORT,'ORDER_LOCKED'); END;
CREATE TRIGGER ec_order_refresh_audit_lock BEFORE UPDATE ON ec_order_refresh_audit WHEN OLD.applied!=0 OR NEW.applied!=1 OR NEW.id!=OLD.id OR NEW.package_id!=OLD.package_id OR NEW.source_record_id!=OLD.source_record_id OR NEW.old_package_json!=OLD.old_package_json OR NEW.old_lines_json!=OLD.old_lines_json OR NEW.new_fingerprint!=OLD.new_fingerprint OR NEW.created_at!=OLD.created_at BEGIN SELECT RAISE(ABORT,'ORDER_REFRESH_AUDIT_LOCKED'); END;
CREATE TRIGGER ec_order_refresh_audit_delete BEFORE DELETE ON ec_order_refresh_audit BEGIN SELECT RAISE(ABORT,'ORDER_REFRESH_AUDIT_LOCKED'); END;
