CREATE TABLE ec_catalog_mappings(id TEXT PRIMARY KEY,source TEXT NOT NULL CHECK(source IN('trendyol','hepsiburada','purchase','other')),supplier_id TEXT NOT NULL DEFAULT '',match_by TEXT NOT NULL DEFAULT 'code' CHECK(match_by IN('code','name')),match_value TEXT NOT NULL,external_code TEXT NOT NULL,external_name TEXT NOT NULL DEFAULT '',source_unit TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 0 CHECK(active IN(0,1)),version INTEGER NOT NULL CHECK(version>0),replaces_id TEXT REFERENCES ec_catalog_mappings(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,archived_at TEXT,CHECK(source!='purchase' OR (supplier_id!='' AND source_unit!='')),CHECK(source='purchase' OR supplier_id=''));
CREATE UNIQUE INDEX ec_catalog_active ON ec_catalog_mappings(source,supplier_id,match_by,match_value,source_unit) WHERE active=1;
CREATE TABLE ec_catalog_mapping_components(id TEXT PRIMARY KEY,mapping_id TEXT NOT NULL REFERENCES ec_catalog_mappings(id),product_id TEXT NOT NULL REFERENCES ec_products(id),quantity_milli INTEGER NOT NULL CHECK(quantity_milli>0),revenue_share_bps INTEGER NOT NULL CHECK(revenue_share_bps BETWEEN 0 AND 10000),UNIQUE(mapping_id,product_id));
CREATE INDEX ec_catalog_component_product ON ec_catalog_mapping_components(product_id);
CREATE TABLE ec_catalog_mapping_audit(id TEXT PRIMARY KEY,mapping_id TEXT NOT NULL REFERENCES ec_catalog_mappings(id),action TEXT NOT NULL CHECK(action IN('created','archived','replaced')),previous_id TEXT REFERENCES ec_catalog_mappings(id),snapshot_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TRIGGER ec_catalog_activate BEFORE UPDATE OF active ON ec_catalog_mappings WHEN NEW.active=1 BEGIN
 SELECT CASE WHEN OLD.archived_at IS NOT NULL OR (SELECT COUNT(*) FROM ec_catalog_mapping_components WHERE mapping_id=NEW.id) NOT BETWEEN 1 AND 10 OR (SELECT SUM(revenue_share_bps) FROM ec_catalog_mapping_components WHERE mapping_id=NEW.id)!=10000 THEN RAISE(ABORT,'CATALOG_INVALID_COMPONENTS') END;
 SELECT CASE WHEN NEW.source='purchase' AND ((SELECT COUNT(*) FROM ec_catalog_mapping_components WHERE mapping_id=NEW.id)!=1 OR NOT EXISTS(SELECT 1 FROM ec_suppliers WHERE id=NEW.supplier_id)) THEN RAISE(ABORT,'CATALOG_INVALID_SUPPLIER') END;
END;
CREATE TRIGGER ec_catalog_immutable BEFORE UPDATE ON ec_catalog_mappings WHEN NEW.id IS NOT OLD.id OR NEW.source IS NOT OLD.source OR NEW.supplier_id IS NOT OLD.supplier_id OR NEW.match_by IS NOT OLD.match_by OR NEW.match_value IS NOT OLD.match_value OR NEW.external_code IS NOT OLD.external_code OR NEW.external_name IS NOT OLD.external_name OR NEW.source_unit IS NOT OLD.source_unit OR NEW.version IS NOT OLD.version OR NEW.replaces_id IS NOT OLD.replaces_id OR NEW.created_at IS NOT OLD.created_at OR OLD.archived_at IS NOT NULL OR (OLD.active=1 AND (NEW.active!=0 OR NEW.archived_at IS NULL)) BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_no_delete BEFORE DELETE ON ec_catalog_mappings BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_component_insert BEFORE INSERT ON ec_catalog_mapping_components WHEN (SELECT active FROM ec_catalog_mappings WHERE id=NEW.mapping_id)!=0 OR (SELECT archived_at FROM ec_catalog_mappings WHERE id=NEW.mapping_id) IS NOT NULL BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_component_update BEFORE UPDATE ON ec_catalog_mapping_components BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_component_delete BEFORE DELETE ON ec_catalog_mapping_components BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_audit_update BEFORE UPDATE ON ec_catalog_mapping_audit BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER ec_catalog_audit_delete BEFORE DELETE ON ec_catalog_mapping_audit BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
ALTER TABLE ec_purchase_lines ADD COLUMN catalog_mapping_id TEXT REFERENCES ec_catalog_mappings(id);

CREATE TABLE lp_catalog_mappings(id TEXT PRIMARY KEY,source TEXT NOT NULL CHECK(source IN('trendyol','hepsiburada','purchase','other')),supplier_id TEXT NOT NULL DEFAULT '',match_by TEXT NOT NULL DEFAULT 'code' CHECK(match_by IN('code','name')),match_value TEXT NOT NULL,external_code TEXT NOT NULL,external_name TEXT NOT NULL DEFAULT '',source_unit TEXT NOT NULL DEFAULT '',active INTEGER NOT NULL DEFAULT 0 CHECK(active IN(0,1)),version INTEGER NOT NULL CHECK(version>0),replaces_id TEXT REFERENCES lp_catalog_mappings(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,archived_at TEXT,CHECK(source!='purchase' OR (supplier_id!='' AND source_unit!='')),CHECK(source='purchase' OR supplier_id=''));
CREATE UNIQUE INDEX lp_catalog_active ON lp_catalog_mappings(source,supplier_id,match_by,match_value,source_unit) WHERE active=1;
CREATE TABLE lp_catalog_mapping_components(id TEXT PRIMARY KEY,mapping_id TEXT NOT NULL REFERENCES lp_catalog_mappings(id),product_id TEXT NOT NULL REFERENCES products(id),quantity_milli INTEGER NOT NULL CHECK(quantity_milli>0),revenue_share_bps INTEGER NOT NULL CHECK(revenue_share_bps BETWEEN 0 AND 10000),UNIQUE(mapping_id,product_id));
CREATE INDEX lp_catalog_component_product ON lp_catalog_mapping_components(product_id);
CREATE TABLE lp_catalog_mapping_audit(id TEXT PRIMARY KEY,mapping_id TEXT NOT NULL REFERENCES lp_catalog_mappings(id),action TEXT NOT NULL CHECK(action IN('created','archived','replaced')),previous_id TEXT REFERENCES lp_catalog_mappings(id),snapshot_json TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TRIGGER lp_catalog_activate BEFORE UPDATE OF active ON lp_catalog_mappings WHEN NEW.active=1 BEGIN
 SELECT CASE WHEN OLD.archived_at IS NOT NULL OR (SELECT COUNT(*) FROM lp_catalog_mapping_components WHERE mapping_id=NEW.id) NOT BETWEEN 1 AND 10 OR (SELECT SUM(revenue_share_bps) FROM lp_catalog_mapping_components WHERE mapping_id=NEW.id)!=10000 THEN RAISE(ABORT,'CATALOG_INVALID_COMPONENTS') END;
 SELECT CASE WHEN NEW.source='purchase' AND ((SELECT COUNT(*) FROM lp_catalog_mapping_components WHERE mapping_id=NEW.id)!=1 OR NOT EXISTS(SELECT 1 FROM lp_suppliers WHERE id=NEW.supplier_id)) THEN RAISE(ABORT,'CATALOG_INVALID_SUPPLIER') END;
END;
CREATE TRIGGER lp_catalog_immutable BEFORE UPDATE ON lp_catalog_mappings WHEN NEW.id IS NOT OLD.id OR NEW.source IS NOT OLD.source OR NEW.supplier_id IS NOT OLD.supplier_id OR NEW.match_by IS NOT OLD.match_by OR NEW.match_value IS NOT OLD.match_value OR NEW.external_code IS NOT OLD.external_code OR NEW.external_name IS NOT OLD.external_name OR NEW.source_unit IS NOT OLD.source_unit OR NEW.version IS NOT OLD.version OR NEW.replaces_id IS NOT OLD.replaces_id OR NEW.created_at IS NOT OLD.created_at OR OLD.archived_at IS NOT NULL OR (OLD.active=1 AND (NEW.active!=0 OR NEW.archived_at IS NULL)) BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_no_delete BEFORE DELETE ON lp_catalog_mappings BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_component_insert BEFORE INSERT ON lp_catalog_mapping_components WHEN (SELECT active FROM lp_catalog_mappings WHERE id=NEW.mapping_id)!=0 OR (SELECT archived_at FROM lp_catalog_mappings WHERE id=NEW.mapping_id) IS NOT NULL BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_component_update BEFORE UPDATE ON lp_catalog_mapping_components BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_component_delete BEFORE DELETE ON lp_catalog_mapping_components BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_audit_update BEFORE UPDATE ON lp_catalog_mapping_audit BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
CREATE TRIGGER lp_catalog_audit_delete BEFORE DELETE ON lp_catalog_mapping_audit BEGIN SELECT RAISE(ABORT,'CATALOG_IMMUTABLE'); END;
ALTER TABLE lp_purchase_lines ADD COLUMN catalog_mapping_id TEXT REFERENCES lp_catalog_mappings(id);
