-- Preserve the supplier line while allocating its physical variants before posting.

CREATE TABLE ec_purchase_line_splits(id TEXT PRIMARY KEY,invoice_id TEXT NOT NULL REFERENCES ec_purchase_invoices(id),original_line_id TEXT NOT NULL,original_json TEXT NOT NULL CHECK(json_valid(original_json)),allocations_json TEXT NOT NULL CHECK(json_valid(allocations_json)),reason TEXT NOT NULL,stock_unit TEXT NOT NULL,total_quantity_milli INTEGER NOT NULL CHECK(total_quantity_milli>0),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','reversed')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX ec_split_active ON ec_purchase_line_splits(original_line_id) WHERE status='active';
ALTER TABLE ec_purchase_lines ADD COLUMN split_id TEXT REFERENCES ec_purchase_line_splits(id);
CREATE TRIGGER ec_split_validate BEFORE INSERT ON ec_purchase_line_splits BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.original_line_id AND l.invoice_id=NEW.invoice_id AND i.status='draft' AND l.line_type='product' AND l.split_id IS NULL AND l.net_cents=json_extract(NEW.original_json,'$.net_cents') AND l.tax_cents=json_extract(NEW.original_json,'$.tax_cents') AND l.invoice_quantity=json_extract(NEW.original_json,'$.invoice_quantity') AND l.invoice_unit=json_extract(NEW.original_json,'$.invoice_unit') AND l.product_id IS json_extract(NEW.original_json,'$.product_id') AND l.quantity_milli IS json_extract(NEW.original_json,'$.quantity_milli') AND l.catalog_mapping_id IS json_extract(NEW.original_json,'$.catalog_mapping_id')) THEN RAISE(ABORT,'SPLIT_CHANGED') END;
 SELECT CASE WHEN json_array_length(NEW.allocations_json)<2 OR json_array_length(NEW.allocations_json)>20 OR (SELECT COUNT(*) FROM ec_purchase_lines WHERE invoice_id=NEW.invoice_id)-1+json_array_length(NEW.allocations_json)>40 THEN RAISE(ABORT,'SPLIT_LIMIT') END;
 SELECT CASE WHEN (SELECT SUM(json_extract(value,'$.quantity_milli')) FROM json_each(NEW.allocations_json))!=NEW.total_quantity_milli OR (SELECT SUM(json_extract(value,'$.net_cents')) FROM json_each(NEW.allocations_json))!=json_extract(NEW.original_json,'$.net_cents') OR (SELECT SUM(json_extract(value,'$.tax_cents')) FROM json_each(NEW.allocations_json))!=json_extract(NEW.original_json,'$.tax_cents') THEN RAISE(ABORT,'SPLIT_TOTAL') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM json_each(NEW.allocations_json) a LEFT JOIN ec_products p ON p.id=json_extract(a.value,'$.product_id') WHERE p.id IS NULL OR p.stock_unit!=NEW.stock_unit) THEN RAISE(ABORT,'SPLIT_UNIT') END;
END;
CREATE TRIGGER ec_split_apply AFTER INSERT ON ec_purchase_line_splits BEGIN
 DELETE FROM ec_purchase_lines WHERE id=NEW.original_line_id;
 INSERT INTO ec_purchase_lines(id,invoice_id,description,external_code,invoice_quantity,invoice_unit,product_id,quantity_milli,net_cents,tax_cents,line_type,split_id)
 SELECT json_extract(value,'$.id'),NEW.invoice_id,json_extract(NEW.original_json,'$.description')||' / '||json_extract(value,'$.name'),'',json_extract(value,'$.invoice_quantity'),json_extract(NEW.original_json,'$.invoice_unit'),json_extract(value,'$.product_id'),json_extract(value,'$.quantity_milli'),json_extract(value,'$.net_cents'),json_extract(value,'$.tax_cents'),'product',NEW.id FROM json_each(NEW.allocations_json);
END;
CREATE TRIGGER ec_split_lock BEFORE UPDATE ON ec_purchase_line_splits BEGIN
 SELECT CASE WHEN OLD.status!='active' OR NEW.status!='reversed' OR NOT EXISTS(SELECT 1 FROM ec_purchase_invoices WHERE id=OLD.invoice_id AND status='draft') OR NEW.original_json!=OLD.original_json OR NEW.allocations_json!=OLD.allocations_json OR NEW.invoice_id!=OLD.invoice_id OR NEW.id!=OLD.id OR NEW.original_line_id!=OLD.original_line_id OR NEW.reason!=OLD.reason OR NEW.stock_unit!=OLD.stock_unit OR NEW.total_quantity_milli!=OLD.total_quantity_milli THEN RAISE(ABORT,'SPLIT_LOCKED') END;
END;
CREATE TRIGGER ec_split_undo AFTER UPDATE OF status ON ec_purchase_line_splits WHEN NEW.status='reversed' BEGIN
 DELETE FROM ec_purchase_lines WHERE split_id=NEW.id;
 INSERT INTO ec_purchase_lines(id,invoice_id,description,external_code,invoice_quantity,invoice_unit,product_id,quantity_milli,net_cents,tax_cents,line_type,expense_category,expense_treatment,catalog_mapping_id)
 VALUES(NEW.original_line_id,NEW.invoice_id,json_extract(NEW.original_json,'$.description'),json_extract(NEW.original_json,'$.external_code'),json_extract(NEW.original_json,'$.invoice_quantity'),json_extract(NEW.original_json,'$.invoice_unit'),json_extract(NEW.original_json,'$.product_id'),json_extract(NEW.original_json,'$.quantity_milli'),json_extract(NEW.original_json,'$.net_cents'),json_extract(NEW.original_json,'$.tax_cents'),'product',json_extract(NEW.original_json,'$.expense_category'),json_extract(NEW.original_json,'$.expense_treatment'),json_extract(NEW.original_json,'$.catalog_mapping_id'));
END;
CREATE TRIGGER ec_split_no_delete BEFORE DELETE ON ec_purchase_line_splits BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER ec_split_line_guard BEFORE UPDATE ON ec_purchase_lines WHEN OLD.split_id IS NOT NULL AND (NEW.product_id IS NOT OLD.product_id OR NEW.quantity_milli IS NOT OLD.quantity_milli OR NEW.net_cents!=OLD.net_cents OR NEW.tax_cents!=OLD.tax_cents OR NEW.line_type!=OLD.line_type OR NEW.catalog_mapping_id IS NOT OLD.catalog_mapping_id OR NEW.split_id IS NOT OLD.split_id) BEGIN SELECT RAISE(ABORT,'SPLIT_LOCKED'); END;

CREATE TABLE lp_purchase_line_splits(id TEXT PRIMARY KEY,invoice_id TEXT NOT NULL REFERENCES lp_purchase_invoices(id),original_line_id TEXT NOT NULL,original_json TEXT NOT NULL CHECK(json_valid(original_json)),allocations_json TEXT NOT NULL CHECK(json_valid(allocations_json)),reason TEXT NOT NULL,stock_unit TEXT NOT NULL,total_quantity_milli INTEGER NOT NULL CHECK(total_quantity_milli>0),status TEXT NOT NULL DEFAULT 'active' CHECK(status IN ('active','reversed')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX lp_split_active ON lp_purchase_line_splits(original_line_id) WHERE status='active';
ALTER TABLE lp_purchase_lines ADD COLUMN split_id TEXT REFERENCES lp_purchase_line_splits(id);
CREATE TRIGGER lp_split_validate BEFORE INSERT ON lp_purchase_line_splits BEGIN
 SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM lp_purchase_lines l JOIN lp_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.original_line_id AND l.invoice_id=NEW.invoice_id AND i.status='draft' AND l.line_type='product' AND l.split_id IS NULL AND l.net_cents=json_extract(NEW.original_json,'$.net_cents') AND l.tax_cents=json_extract(NEW.original_json,'$.tax_cents') AND l.invoice_quantity=json_extract(NEW.original_json,'$.invoice_quantity') AND l.invoice_unit=json_extract(NEW.original_json,'$.invoice_unit') AND l.product_id IS json_extract(NEW.original_json,'$.product_id') AND l.quantity_milli IS json_extract(NEW.original_json,'$.quantity_milli') AND l.catalog_mapping_id IS json_extract(NEW.original_json,'$.catalog_mapping_id')) THEN RAISE(ABORT,'SPLIT_CHANGED') END;
 SELECT CASE WHEN json_array_length(NEW.allocations_json)<2 OR json_array_length(NEW.allocations_json)>20 OR (SELECT COUNT(*) FROM lp_purchase_lines WHERE invoice_id=NEW.invoice_id)-1+json_array_length(NEW.allocations_json)>40 THEN RAISE(ABORT,'SPLIT_LIMIT') END;
 SELECT CASE WHEN (SELECT SUM(json_extract(value,'$.quantity_milli')) FROM json_each(NEW.allocations_json))!=NEW.total_quantity_milli OR (SELECT SUM(json_extract(value,'$.net_cents')) FROM json_each(NEW.allocations_json))!=json_extract(NEW.original_json,'$.net_cents') OR (SELECT SUM(json_extract(value,'$.tax_cents')) FROM json_each(NEW.allocations_json))!=json_extract(NEW.original_json,'$.tax_cents') THEN RAISE(ABORT,'SPLIT_TOTAL') END;
 SELECT CASE WHEN EXISTS(SELECT 1 FROM json_each(NEW.allocations_json) a LEFT JOIN products p ON p.id=json_extract(a.value,'$.product_id') WHERE p.id IS NULL OR p.stock_unit!=NEW.stock_unit) THEN RAISE(ABORT,'SPLIT_UNIT') END;
END;
CREATE TRIGGER lp_split_apply AFTER INSERT ON lp_purchase_line_splits BEGIN
 DELETE FROM lp_purchase_lines WHERE id=NEW.original_line_id;
 INSERT INTO lp_purchase_lines(id,invoice_id,description,external_code,invoice_quantity,invoice_unit,product_id,quantity_milli,net_cents,tax_cents,line_type,split_id)
 SELECT json_extract(value,'$.id'),NEW.invoice_id,json_extract(NEW.original_json,'$.description')||' / '||json_extract(value,'$.name'),'',json_extract(value,'$.invoice_quantity'),json_extract(NEW.original_json,'$.invoice_unit'),json_extract(value,'$.product_id'),json_extract(value,'$.quantity_milli'),json_extract(value,'$.net_cents'),json_extract(value,'$.tax_cents'),'product',NEW.id FROM json_each(NEW.allocations_json);
END;
CREATE TRIGGER lp_split_lock BEFORE UPDATE ON lp_purchase_line_splits BEGIN
 SELECT CASE WHEN OLD.status!='active' OR NEW.status!='reversed' OR NOT EXISTS(SELECT 1 FROM lp_purchase_invoices WHERE id=OLD.invoice_id AND status='draft') OR NEW.original_json!=OLD.original_json OR NEW.allocations_json!=OLD.allocations_json OR NEW.invoice_id!=OLD.invoice_id OR NEW.id!=OLD.id OR NEW.original_line_id!=OLD.original_line_id OR NEW.reason!=OLD.reason OR NEW.stock_unit!=OLD.stock_unit OR NEW.total_quantity_milli!=OLD.total_quantity_milli THEN RAISE(ABORT,'SPLIT_LOCKED') END;
END;
CREATE TRIGGER lp_split_undo AFTER UPDATE OF status ON lp_purchase_line_splits WHEN NEW.status='reversed' BEGIN
 DELETE FROM lp_purchase_lines WHERE split_id=NEW.id;
 INSERT INTO lp_purchase_lines(id,invoice_id,description,external_code,invoice_quantity,invoice_unit,product_id,quantity_milli,net_cents,tax_cents,line_type,expense_category,expense_treatment,catalog_mapping_id)
 VALUES(NEW.original_line_id,NEW.invoice_id,json_extract(NEW.original_json,'$.description'),json_extract(NEW.original_json,'$.external_code'),json_extract(NEW.original_json,'$.invoice_quantity'),json_extract(NEW.original_json,'$.invoice_unit'),json_extract(NEW.original_json,'$.product_id'),json_extract(NEW.original_json,'$.quantity_milli'),json_extract(NEW.original_json,'$.net_cents'),json_extract(NEW.original_json,'$.tax_cents'),'product',json_extract(NEW.original_json,'$.expense_category'),json_extract(NEW.original_json,'$.expense_treatment'),json_extract(NEW.original_json,'$.catalog_mapping_id'));
END;
CREATE TRIGGER lp_split_no_delete BEFORE DELETE ON lp_purchase_line_splits BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER lp_split_line_guard BEFORE UPDATE ON lp_purchase_lines WHEN OLD.split_id IS NOT NULL AND (NEW.product_id IS NOT OLD.product_id OR NEW.quantity_milli IS NOT OLD.quantity_milli OR NEW.net_cents!=OLD.net_cents OR NEW.tax_cents!=OLD.tax_cents OR NEW.line_type!=OLD.line_type OR NEW.catalog_mapping_id IS NOT OLD.catalog_mapping_id OR NEW.split_id IS NOT OLD.split_id) BEGIN SELECT RAISE(ABORT,'SPLIT_LOCKED'); END;
