CREATE TABLE ec_purchase_adjustments(
 id TEXT PRIMARY KEY,line_id TEXT NOT NULL REFERENCES ec_purchase_lines(id),kind TEXT NOT NULL CHECK(kind IN ('price','service','cancel')),
 quantity_milli INTEGER NOT NULL DEFAULT 0 CHECK(typeof(quantity_milli)='integer' AND quantity_milli>=0),
 net_cents INTEGER NOT NULL CHECK(typeof(net_cents)='integer' AND ABS(net_cents)<=10000000000),tax_cents INTEGER NOT NULL CHECK(typeof(tax_cents)='integer' AND ABS(tax_cents)<=10000000000),
 stock_cents INTEGER NOT NULL DEFAULT 0 CHECK(typeof(stock_cents)='integer' AND ABS(stock_cents)<=ABS(net_cents) AND stock_cents*1.0*net_cents>=0),
 reference TEXT NOT NULL,operation_id TEXT NOT NULL,occurred_on TEXT NOT NULL,reason TEXT NOT NULL,reversal_of TEXT UNIQUE REFERENCES ec_purchase_adjustments(id),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(line_id,reference)
);
CREATE INDEX ec_purchase_adjustments_line ON ec_purchase_adjustments(line_id);
CREATE VIEW ec_active_purchase_adjustments AS SELECT a.* FROM ec_purchase_adjustments a WHERE a.reversal_of IS NULL AND NOT EXISTS(SELECT 1 FROM ec_purchase_adjustments r WHERE r.reversal_of=a.id);
CREATE VIEW ec_purchase_line_limits AS SELECT l.id,
 l.net_cents-COALESCE((SELECT SUM(net_cents) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind IN ('price','service')),0) effective_net,
 l.tax_cents-COALESCE((SELECT SUM(tax_cents) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind IN ('price','service')),0) effective_tax,
 COALESCE((SELECT SUM(quantity_milli) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind='cancel'),0) cancelled_milli,
 COALESCE((SELECT SUM(quantity_milli) FROM ec_active_purchase_returns WHERE line_id=l.id),0)+COALESCE((SELECT SUM(quantity_milli) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind='cancel'),0) closed_milli,
 COALESCE((SELECT SUM(net_cents) FROM ec_active_purchase_returns WHERE line_id=l.id),0)+COALESCE((SELECT SUM(net_cents) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind='cancel'),0) closed_net,
 COALESCE((SELECT SUM(tax_cents) FROM ec_active_purchase_returns WHERE line_id=l.id),0)+COALESCE((SELECT SUM(tax_cents) FROM ec_active_purchase_adjustments WHERE line_id=l.id AND kind='cancel'),0) closed_tax
 FROM ec_purchase_lines l;
CREATE TRIGGER ec_adjustment_validate BEFORE INSERT ON ec_purchase_adjustments BEGIN
 SELECT iif(NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.line_id AND i.status='posted' AND i.invoice_date<=NEW.occurred_on AND ((NEW.kind='service' AND l.line_type='expense') OR (NEW.kind IN ('price','cancel') AND l.line_type='product'))),RAISE(ABORT,'ADJUSTMENT_INVALID'),NULL);
 SELECT iif(EXISTS(SELECT 1 FROM ec_purchase_adjustments a JOIN ec_purchase_lines l ON l.id=a.line_id WHERE l.invoice_id=(SELECT invoice_id FROM ec_purchase_lines WHERE id=NEW.line_id) AND a.reference=NEW.reference AND a.operation_id!=NEW.operation_id),RAISE(ABORT,'ADJUSTMENT_DUPLICATE'),NULL);
 SELECT iif((NEW.kind='cancel' AND (NEW.quantity_milli<=0 OR NEW.stock_cents!=0 OR NEW.net_cents<0 OR NEW.tax_cents<0)) OR (NEW.kind!='cancel' AND (NEW.quantity_milli!=0 OR NEW.net_cents*1.0*NEW.tax_cents<0 OR NEW.net_cents+NEW.tax_cents=0)) OR (NEW.kind='service' AND NEW.stock_cents!=0),RAISE(ABORT,'ADJUSTMENT_INVALID'),NULL);
 SELECT iif(NEW.reversal_of IS NOT NULL AND NOT EXISTS(SELECT 1 FROM ec_active_purchase_adjustments a WHERE a.id=NEW.reversal_of AND a.line_id=NEW.line_id AND a.kind=NEW.kind AND a.quantity_milli=NEW.quantity_milli AND a.net_cents=NEW.net_cents AND a.tax_cents=NEW.tax_cents AND a.stock_cents=NEW.stock_cents AND a.occurred_on<=NEW.occurred_on),RAISE(ABORT,'ADJUSTMENT_REVERSED'),NULL);
 SELECT iif(NEW.kind='price' AND (EXISTS(SELECT 1 FROM ec_active_purchase_returns WHERE line_id=NEW.line_id) OR EXISTS(SELECT 1 FROM ec_active_purchase_adjustments WHERE line_id=NEW.line_id AND kind='cancel')),RAISE(ABORT,'ADJUSTMENT_CLOSED_LINE'),NULL);
 SELECT iif(NEW.kind IN ('price','service') AND EXISTS(SELECT 1 FROM ec_purchase_line_limits v WHERE v.id=NEW.line_id AND (v.effective_net-iif(NEW.reversal_of IS NULL,NEW.net_cents,-NEW.net_cents)<0 OR v.effective_tax-iif(NEW.reversal_of IS NULL,NEW.tax_cents,-NEW.tax_cents)<0)),RAISE(ABORT,'ADJUSTMENT_EXCEEDS'),NULL);
 SELECT iif(NEW.kind='service' AND (SELECT expense_treatment FROM ec_purchase_lines WHERE id=NEW.line_id)='sales_fee' AND COALESCE((SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE invoice_line_id=NEW.line_id AND reversed_at IS NULL),0)>(SELECT effective_net-iif(NEW.reversal_of IS NULL,NEW.net_cents,-NEW.net_cents) FROM ec_purchase_line_limits WHERE id=NEW.line_id),RAISE(ABORT,'ADJUSTMENT_ALLOCATED_FEE'),NULL);
 SELECT iif(NEW.stock_cents!=0 AND (SELECT quantity_milli FROM ec_purchase_lines WHERE id=NEW.line_id)!=COALESCE((SELECT SUM(quantity_milli) FROM ec_effective_receipts WHERE line_id=NEW.line_id),0),RAISE(ABORT,'ADJUSTMENT_RECEIVE_FIRST'),NULL);
 SELECT iif(NEW.stock_cents!=0 AND NOT EXISTS(SELECT 1 FROM ec_stock_balances b JOIN ec_purchase_lines l ON l.product_id=b.product_id WHERE l.id=NEW.line_id AND b.quantity_milli>0 AND b.value_cents-iif(NEW.reversal_of IS NULL,NEW.stock_cents,-NEW.stock_cents)>=0),RAISE(ABORT,'ADJUSTMENT_STOCK_VALUE'),NULL);
 SELECT iif(NEW.kind='cancel' AND NEW.reversal_of IS NULL AND NEW.quantity_milli+(SELECT cancelled_milli FROM ec_purchase_line_limits WHERE id=NEW.line_id)+COALESCE((SELECT SUM(quantity_milli) FROM ec_effective_receipts WHERE line_id=NEW.line_id),0)>(SELECT quantity_milli FROM ec_purchase_lines WHERE id=NEW.line_id),RAISE(ABORT,'ADJUSTMENT_CANCEL_QUANTITY'),NULL);
 SELECT iif(NEW.kind='cancel' AND NEW.reversal_of IS NULL AND NOT EXISTS(SELECT 1 FROM ec_purchase_line_limits v JOIN ec_purchase_lines l ON l.id=v.id WHERE v.id=NEW.line_id AND NEW.net_cents=CAST(ROUND(v.effective_net*(NEW.quantity_milli+v.closed_milli)/(l.quantity_milli*1.0)) AS INTEGER)-v.closed_net AND NEW.tax_cents=CAST(ROUND(v.effective_tax*(NEW.quantity_milli+v.closed_milli)/(l.quantity_milli*1.0)) AS INTEGER)-v.closed_tax),RAISE(ABORT,'ADJUSTMENT_EXCEEDS'),NULL);
 SELECT iif(NEW.reversal_of IS NOT NULL AND EXISTS(SELECT 1 FROM ec_payment_allocations a WHERE (a.positive_entry_id='adjustment:'||NEW.reversal_of OR a.negative_entry_id='adjustment:'||NEW.reversal_of) AND NOT EXISTS(SELECT 1 FROM ec_allocation_reversals r WHERE r.allocation_id=a.id)),RAISE(ABORT,'ADJUSTMENT_PARTY_ALLOCATED'),NULL);
END;
CREATE TRIGGER ec_adjustment_apply AFTER INSERT ON ec_purchase_adjustments BEGIN
 UPDATE ec_stock_balances SET value_cents=value_cents-iif(NEW.reversal_of IS NULL,NEW.stock_cents,-NEW.stock_cents) WHERE product_id=(SELECT product_id FROM ec_purchase_lines WHERE id=NEW.line_id) AND NEW.stock_cents!=0;
 INSERT INTO ec_party_entries(id,party_id,amount_cents,occurred_on,reference,description,source_key,source) SELECT 'adjustment:'||NEW.id,i.supplier_id,iif(NEW.reversal_of IS NULL,NEW.net_cents+NEW.tax_cents,-NEW.net_cents-NEW.tax_cents),NEW.occurred_on,NEW.reference,'Alış düzeltmesi · '||i.invoice_no||' · '||NEW.reason,'adjustment:'||NEW.id,'invoice' FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.line_id AND NEW.net_cents+NEW.tax_cents!=0;
 INSERT INTO ec_payment_allocations(id,positive_entry_id,negative_entry_id,amount_cents,reference) SELECT 'adjustment-reverse:'||NEW.id,'adjustment:'||iif(NEW.net_cents+NEW.tax_cents>0,NEW.reversal_of,NEW.id),'adjustment:'||iif(NEW.net_cents+NEW.tax_cents>0,NEW.id,NEW.reversal_of),ABS(NEW.net_cents+NEW.tax_cents),'adjustment-reverse:'||NEW.id WHERE NEW.reversal_of IS NOT NULL AND NEW.net_cents+NEW.tax_cents!=0;
END;
CREATE TRIGGER ec_adjustments_no_update BEFORE UPDATE ON ec_purchase_adjustments BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER ec_adjustments_no_delete BEFORE DELETE ON ec_purchase_adjustments BEGIN SELECT RAISE(ABORT,'IMMUTABLE_LEDGER'); END;
CREATE TRIGGER ec_adjusted_fee_limit BEFORE INSERT ON ec_fee_allocations BEGIN SELECT iif(NEW.amount_cents+COALESCE((SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE invoice_line_id=NEW.invoice_line_id AND reversed_at IS NULL),0)>(SELECT effective_net FROM ec_purchase_line_limits WHERE id=NEW.invoice_line_id),RAISE(ABORT,'ADJUSTMENT_ALLOCATED_FEE'),NULL); END;
CREATE TRIGGER ec_adjusted_receipt_limit BEFORE INSERT ON ec_goods_receipts BEGIN SELECT iif(NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM ec_effective_receipts WHERE line_id=NEW.line_id),0)+(SELECT cancelled_milli FROM ec_purchase_line_limits WHERE id=NEW.line_id)>(SELECT quantity_milli FROM ec_purchase_lines WHERE id=NEW.line_id),RAISE(ABORT,'RECEIPT_EXCEEDS_INVOICE'),NULL); END;
CREATE TRIGGER ec_adjusted_receipt_reverse BEFORE INSERT ON ec_receipt_reversals BEGIN SELECT iif(EXISTS(SELECT 1 FROM ec_active_purchase_adjustments a JOIN ec_goods_receipts g ON g.line_id=a.line_id WHERE g.id=NEW.receipt_id AND a.kind='price' AND a.stock_cents!=0),RAISE(ABORT,'RECEIPT_REVERSAL_COST'),NULL); END;

DROP TRIGGER ec_purchase_return_validate;
CREATE TRIGGER ec_purchase_return_validate BEFORE INSERT ON ec_purchase_returns BEGIN
 SELECT iif(EXISTS(SELECT 1 FROM ec_purchase_returns r JOIN ec_purchase_lines l ON l.id=r.line_id WHERE l.invoice_id=(SELECT invoice_id FROM ec_purchase_lines WHERE id=NEW.line_id) AND r.reference=NEW.reference AND r.operation_id!=NEW.operation_id),RAISE(ABORT,'PURCHASE_RETURN_REVERSED'),NULL);
 SELECT iif(NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.line_id AND l.line_type='product' AND i.status='posted' AND i.invoice_date<=NEW.occurred_on),RAISE(ABORT,'PURCHASE_RETURN_INVALID'),NULL);
 SELECT iif(NEW.reversal_of IS NULL AND NEW.quantity_milli+COALESCE((SELECT SUM(quantity_milli) FROM ec_active_purchase_returns WHERE line_id=NEW.line_id),0)>COALESCE((SELECT SUM(quantity_milli) FROM ec_effective_receipts WHERE line_id=NEW.line_id AND occurred_on<=NEW.occurred_on),0),RAISE(ABORT,'PURCHASE_RETURN_QUANTITY'),NULL);
 SELECT iif(NEW.reversal_of IS NULL AND NOT EXISTS(SELECT 1 FROM ec_purchase_line_limits v JOIN ec_purchase_lines l ON l.id=v.id WHERE l.id=NEW.line_id AND NEW.net_cents=CAST(ROUND(v.effective_net*(NEW.quantity_milli+v.closed_milli)/(l.quantity_milli*1.0)) AS INTEGER)-v.closed_net AND NEW.tax_cents=CAST(ROUND(v.effective_tax*(NEW.quantity_milli+v.closed_milli)/(l.quantity_milli*1.0)) AS INTEGER)-v.closed_tax),RAISE(ABORT,'PURCHASE_RETURN_VALUE'),NULL);
 SELECT iif(NEW.reversal_of IS NULL AND NEW.cost_cents!=(SELECT CAST(ROUND(b.value_cents*1.0*NEW.quantity_milli/MAX(b.quantity_milli,1.0)) AS INTEGER) FROM ec_stock_balances b JOIN ec_purchase_lines l ON l.product_id=b.product_id WHERE l.id=NEW.line_id),RAISE(ABORT,'PURCHASE_RETURN_VALUE'),NULL);
 SELECT iif(NEW.reversal_of IS NOT NULL AND NOT EXISTS(SELECT 1 FROM ec_active_purchase_returns r WHERE r.id=NEW.reversal_of AND r.line_id=NEW.line_id AND r.quantity_milli=NEW.quantity_milli AND r.net_cents=NEW.net_cents AND r.tax_cents=NEW.tax_cents AND r.cost_cents=NEW.cost_cents AND r.occurred_on<=NEW.occurred_on),RAISE(ABORT,'PURCHASE_RETURN_REVERSED'),NULL);
 SELECT iif(NEW.reversal_of IS NOT NULL AND EXISTS(SELECT 1 FROM ec_payment_allocations a WHERE (a.positive_entry_id='purchase-return:'||NEW.reversal_of OR a.negative_entry_id='purchase-return:'||NEW.reversal_of) AND NOT EXISTS(SELECT 1 FROM ec_allocation_reversals x WHERE x.allocation_id=a.id)),RAISE(ABORT,'PURCHASE_RETURN_ALLOCATED'),NULL);
END;
DROP TRIGGER ec_fee_allocation_validate;
CREATE TRIGGER ec_fee_allocation_validate BEFORE INSERT ON ec_fee_allocations BEGIN
 SELECT iif(NOT EXISTS(SELECT 1 FROM ec_purchase_lines l JOIN ec_purchase_invoices i ON i.id=l.invoice_id WHERE l.id=NEW.invoice_line_id AND i.status='posted' AND l.line_type='expense' AND l.expense_treatment='sales_fee' AND NEW.component= CASE WHEN l.expense_category IN ('shipping','commission') THEN l.expense_category ELSE 'other' END ),RAISE(ABORT,'INVALID_FEE_SOURCE'),NULL);
 SELECT iif(NOT EXISTS(SELECT 1 FROM ec_sale_entries WHERE id=NEW.sale_id AND kind='sale'),RAISE(ABORT,'INVALID_FEE_SALE'),NULL);
 SELECT iif(NEW.amount_cents+COALESCE((SELECT SUM(amount_cents) FROM ec_fee_allocations WHERE invoice_line_id=NEW.invoice_line_id AND reversed_at IS NULL),0)>(SELECT effective_net FROM ec_purchase_line_limits WHERE id=NEW.invoice_line_id),RAISE(ABORT,'FEE_OVERALLOCATION'),NULL);
 SELECT iif(NEW.takeover=0 AND NOT EXISTS(SELECT 1 FROM ec_fee_allocations WHERE sale_id=NEW.sale_id AND component=NEW.component AND reversed_at IS NULL) AND (SELECT CASE NEW.component WHEN 'shipping' THEN shipping_cents WHEN 'commission' THEN commission_cents ELSE other_cents END FROM ec_sale_entries WHERE id=NEW.sale_id) IS NOT NULL,RAISE(ABORT,'FEE_TAKEOVER_REQUIRED'),NULL);
 SELECT iif(NEW.reversed_at IS NOT NULL,RAISE(ABORT,'INVALID_FEE_ALLOCATION'),NULL);
END;
