-- Isolated web shop records. Test orders never post into ec_* or lp_* ledgers.
CREATE TABLE ws_customers(id TEXT PRIMARY KEY,email TEXT NOT NULL UNIQUE COLLATE NOCASE,name TEXT NOT NULL,salt TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ws_sessions(token_hash TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES ws_customers(id),expires_at INTEGER NOT NULL);
CREATE INDEX ws_sessions_customer ON ws_sessions(customer_id);
CREATE TABLE ws_catalog(id TEXT PRIMARY KEY,product_id TEXT NOT NULL,name TEXT NOT NULL,size TEXT NOT NULL,image TEXT NOT NULL,category TEXT NOT NULL,price_cents INTEGER NOT NULL CHECK(price_cents>0),stock INTEGER NOT NULL DEFAULT 0 CHECK(stock>=0),active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)));
CREATE TABLE ws_quotes(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES ws_customers(id),snapshot_json TEXT NOT NULL,expires_at INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ws_quotes_expiry ON ws_quotes(expires_at);
CREATE TABLE ws_orders(id TEXT PRIMARY KEY,number TEXT NOT NULL UNIQUE,customer_id TEXT NOT NULL REFERENCES ws_customers(id),quote_id TEXT NOT NULL UNIQUE REFERENCES ws_quotes(id),status TEXT NOT NULL DEFAULT 'new' CHECK(status IN('new','preparing','shipped','delivered','cancelled')),payment_status TEXT NOT NULL DEFAULT 'pending' CHECK(payment_status IN('pending','demo_paid','failed')),is_test INTEGER NOT NULL DEFAULT 1 CHECK(is_test=1),subtotal_cents INTEGER NOT NULL,shipping_cents INTEGER NOT NULL,total_cents INTEGER NOT NULL CHECK(total_cents=subtotal_cents+shipping_cents),snapshot_json TEXT NOT NULL,legal_version TEXT NOT NULL,accepted_at TEXT NOT NULL,carrier TEXT NOT NULL DEFAULT '',tracking TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ws_orders_customer ON ws_orders(customer_id,created_at);
CREATE INDEX ws_orders_status ON ws_orders(status,created_at);
CREATE TABLE ws_order_items(id TEXT PRIMARY KEY,order_id TEXT NOT NULL REFERENCES ws_orders(id),variant_id TEXT NOT NULL REFERENCES ws_catalog(id),name TEXT NOT NULL,size TEXT NOT NULL,qty INTEGER NOT NULL CHECK(qty BETWEEN 1 AND 99),price_cents INTEGER NOT NULL CHECK(price_cents>0),UNIQUE(order_id,variant_id));
CREATE TRIGGER ws_reserve_stock AFTER INSERT ON ws_order_items BEGIN UPDATE ws_catalog SET stock=stock-NEW.qty WHERE id=NEW.variant_id; END;
CREATE TRIGGER ws_restore_stock AFTER UPDATE OF status ON ws_orders WHEN NEW.status='cancelled' AND OLD.status<>'cancelled' BEGIN UPDATE ws_catalog SET stock=stock+COALESCE((SELECT qty FROM ws_order_items WHERE order_id=NEW.id AND variant_id=ws_catalog.id),0) WHERE id IN(SELECT variant_id FROM ws_order_items WHERE order_id=NEW.id); END;
CREATE TRIGGER ws_snapshot_immutable BEFORE UPDATE OF snapshot_json,legal_version,accepted_at,subtotal_cents,shipping_cents,total_cents,customer_id,quote_id,is_test ON ws_orders BEGIN SELECT RAISE(ABORT,'Order evidence is immutable'); END;
CREATE TABLE ws_events(id TEXT PRIMARY KEY,order_id TEXT REFERENCES ws_orders(id),actor TEXT NOT NULL,action TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ws_requests(id TEXT PRIMARY KEY,customer_id TEXT NOT NULL REFERENCES ws_customers(id),order_id TEXT REFERENCES ws_orders(id),kind TEXT NOT NULL CHECK(kind IN('withdrawal','support','privacy')),message TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','reviewing','closed')),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ws_requests_customer ON ws_requests(customer_id,created_at);
