export const LEGAL_VERSION='2026-09-10.draft-1';
export const SELLER={name:'Dekovill Mimarlık İnşaat Taahhüt Gıda Sanayi Ticaret Limited Şirketi',brand:'Lunapot',address:'Sahil Mahallesi Gamze Sokak No:3 D:8 Çiftlikköy / Yalova',taxOffice:'Yalova Vergi Dairesi',taxNumber:'2731455087',mersis:'0273145508700001',registry:'11711',email:'info@lunapot.com',phone:'0850 304 24 12',kep:'Doğrulanacak',chamber:'Doğrulanacak'};
export const LEGAL_DOCS={
 'on-bilgilendirme':{title:'Ön bilgilendirme formu',paragraphs:[
 'Bu sayfa genel taslaktır. Siparişine özel ürünler, miktarlar, vergiler dahil fiyat, teslimat bedeli, toplam, satıcı ve alıcı bilgileri ödeme öncesindeki özette gösterilir; hesap alanında saklanır. Test akışı ödeme borcu doğurmaz.',
 'Satıcının kimlik ve iletişim bilgileri aşağıdadır. Sipariş dilimiz Türkçedir. Siparişten önce adres ve ürün seçimini değiştirebilir, işlemi bırakabilirsin. Gerçek satışa geçildiğinde ödeme yöntemi, taşıyıcı, teslim süresi ve iade adresi burada kesinleştirilecektir.',
 'Genel kural olarak mal tesliminden itibaren 14 gün içinde gerekçe göstermeden cayma bildiriminde bulunabilirsin. Hesabındaki cayma talebi veya satıcı e-postası kullanılabilir; örnek form zorunlu değildir. Kanuni istisnalar varsa ürün bazında önceden açıklanmalıdır.',
 'Satış açılmadan önce şirket kayıtları, gerçek fiyatlar, kargo koşulları ve metinler işletme tarafından teyit edilmelidir. Bu taslakla gerçek tahsilat kapalıdır.']},
 'mesafeli-satis':{title:'Mesafeli satış sözleşmesi',paragraphs:[
 'Taraflar; aşağıda bilgileri bulunan satıcı ile sipariş özetindeki alıcıdır. Konu, sipariş özetinde özellikleri, adedi ve vergiler dahil bedeli gösterilen ürünlerin satışı ve teslimidir. Onaylanan özet bu sözleşmenin ayrılmaz parçasıdır.',
 'Alıcı ödeme öncesinde ürünleri, adresi, teslimat ücretini ve toplamı kontrol eder. Satıcı, onaylanan siparişin kayıtlarını sözleşme sürümü ve tarih ile saklar. Alıcı hesabından siparişe ait nüshayı indirebilir. Test siparişleri gerçek satış veya tahsilat değildir.',
 'Siparişe özel olarak daha kısa süre kararlaştırılmadıkça, mal tesliminde yasal azami süre 30 gündür; kişiye özel hazırlanan malların durumu ayrıca değerlendirilir. İfa imkânsızlaşırsa mevzuata uygun bildirim ve bedel iadesi yapılır. Yalnızca stokta bulunmama ifa imkânsızlığı sayılmaz.',
 'Cayma bildirimi, iade ve ayıplı mal hakları aşağıdaki Cayma ve iade sayfasında açıklanır. Tüketicinin emredici mevzuattan kaynaklanan hakları sınırlandırılamaz. Uyuşmazlıklarda görev ve parasal sınırlara göre tüketici hakem heyetlerine veya tüketici mahkemelerine başvurulabilir; uygulanabildiği hallerde dava şartı arabuluculuk saklıdır.']},
 'cayma-iade':{title:'Cayma, iade ve teslimat',paragraphs:[
 'Cayma bildiriminin ardından ürünü 14 gün içinde geri göndermen gerekir. Belirtilen iade taşıyıcısıyla yapılan iadede masraf tüketiciye yüklenmez; taşıyıcı belirtilmemişse herhangi bir taşıyıcıyla iade masrafı da tüketiciye yüklenemez.',
 'Bedel iadesi, belirtilen taşıyıcıya teslimden; başka taşıyıcı seçilmişse satıcının ürünü teslim almasından itibaren 14 gün içinde yapılır. Teslim edilmemiş üründe süre cayma bildirimiyle başlar. İade, kullanılan ödeme aracına uygun, tüketiciye masraf çıkarmadan yapılır.',
 'Kişisel isteğe göre hazırlanan ürünler gibi kanuni istisnalar ürün bazında açıklanır; standart saksıların tamamı otomatik olarak istisna sayılmaz. Ayıplı mal hakların ayrıca saklıdır. Taşıyıcı ve iade adresi gerçek satış öncesinde doğrulanacaktır.',
 'Örnek bildirim: Satıcıya; aşağıdaki ürünün satış sözleşmesinden caydığımı bildiririm. Sipariş numarası / ürün / sipariş ve teslim tarihi / ad soyad / adres / bildirim tarihi. Kâğıt üzerinde gönderiyorsan imza ekleyebilirsin. Hesabım alanındaki Cayma talebi düğmesiyle kayıt oluşturabilir veya info@lunapot.com adresini kullanabilirsin.']},
 'kvkk':{title:'Kişisel veri aydınlatma metni',paragraphs:[
 'Veri sorumlusu aşağıda kimlik ve iletişim bilgileri bulunan Dekovill Mimarlık İnşaat Taahhüt Gıda Sanayi Ticaret Limited Şirketidir. Üyelik ve sipariş formunda sağladığın ad, e-posta, telefon, teslimat/fatura adresi, sipariş ve talep bilgilerini elektronik ortamda toplarız. Şifre açık biçimde saklanmaz; kart numarası veya CVV bu sistemde toplanmaz.',
 'Hesap ve sipariş işlemleri sözleşmenin kurulması/ifası; zorunlu ticari kayıtlar hukuki yükümlülük; uyuşmazlık delilleri bir hakkın tesisi/kullanılması/korunması; güvenlik ve kötüye kullanım önleme ölçülü meşru menfaat amaç ve sebeplerine dayanır. Aydınlatma bir pazarlama izni değildir; üyelik reklam iznine bağlanmaz.',
 'Veriler görevli personelin yetkisine göre erişilebilir. Gerçek satışta gerekli bilgiler teslimat için taşıyıcıya, tahsilat için ödeme kuruluşuna, faturalama için yetkili hizmet sağlayıcıya ve kanunen yetkili mercilere aktarılabilir. Şu anda bu servisler bağlı değildir; test verileri yerel veritabanında tutulur.',
 'Canlı barındırmada Cloudflare kullanılması planlanmaktadır. Gerçek kişi verileriyle yayından önce alıcılar, saklama planı ve yurt dışına aktarımın Kanunun 9. maddesine uygun mekanizması kesinleştirilerek bu metin güncellenecektir. Genel bir onay kutusu bu işlemlerin yerine geçmez.',
 'Kanunun 11. maddesi kapsamında verilerinin işlenmesini öğrenme, bilgi isteme, amaç ve alıcıları öğrenme, düzeltme, koşulları varsa silme/yok etme, alıcılara bildirim, otomatik analiz sonucuna itiraz ve zararın giderilmesini isteme hakların vardır. Talebini hesabındaki Kişisel veri talebi alanından kaydedebilir; mevzuata uygun başvuru yöntemleriyle şirket adresi veya e-postasına iletebilirsin. Başvurular kural olarak en geç 30 gün içinde cevaplanır.']},
 'gizlilik':{title:'Gizlilik ve hesap güvenliği',paragraphs:[
 'Mağaza hesabı ile işletmenin yönetici hesabı ayrıdır. Başka müşterilerin siparişleri hesabından görüntülenemez. Müşteri ve adres bilgileri web mağaza modülünde yetkili personele gösterilir.',
 'Şifreni kimseyle paylaşma. Çıkış yaptığında oturumun sunucuda sonlandırılır. Şifreni değiştirdiğinde mevcut müşteri oturumların kapatılır. Sipariş belgelerini ortak cihazlara indirirken kendi gizliliğini gözet.',
 'Test akışında yalnızca uydurma deneme bilgileri kullan. Ödeme sayfasında kart alanı bulunmaz. Ödeme sağlayıcısı bağlandığında kart bilgileri sağlayıcının güvenli sayfasına girilecektir.']},
 'cerez':{title:'Çerez ve tarayıcı depolaması',paragraphs:[
 'Bu sürümde reklam, analiz veya sosyal medya takip çerezi bulunmaz. Müşteri girişi için ws_customer oturum çerezi kullanılır; HttpOnly niteliğiyle betik erişimine kapalıdır ve 7 gün içinde sona erer. Çıkışta silinir.',
 'lunapot-unified-preview-selections-v1 adlı sessionStorage kaydı deneme sepeti ve favori ürün kimliklerini aynı sekmede korur; sekme oturumuyla sınırlıdır. Burada şifre, adres veya kart bilgisi saklanmaz.',
 'Zorunlu olmayan takip araçları ileride eklenirse amaçlarına göre ayrı tercih ve geri alma mekanizması sunulmadan yüklenmeyecektir. Şu anda kabul etmeyi zorunlu tutan bir takip çerezi penceresi gösterilmez.']},
 'uyelik':{title:'Üyelik koşulları',paragraphs:[
 'Kendi e-posta adresin ve seçtiğin şifreyle hesap oluşturabilirsin. Bilgilerinin doğruluğundan ve hesabının güvenliğinden sorumlusun. Başkası adına yetkisiz hesap oluşturma veya sistemi kötüye kullanma.',
 'Üyelik siparişlerini ve taleplerini görüntülemene olanak verir. Ticari ileti izni üyelik koşulu değildir. Bu test sürümünde e-posta doğrulama ve şifre sıfırlama gönderim hizmetleri henüz bağlı değildir; canlı üyelik açılmadan tamamlanacaktır.',
 'Hesap veya verilerinle ilgili talebini Hesabım bölümünden iletebilirsin. Saklanması zorunlu kayıtlar dışında silme talepleri uygulanabilir kurallara göre değerlendirilir. Yasal tüketici hakların saklıdır.']},
 'islem-rehberi':{title:'İşlem rehberi',paragraphs:[
 '1. Ürününü seç, boyut ve adedi belirle, sepete ekle. Sepette adedi değiştirebilir veya ürünü kaldırabilirsin.',
 '2. Hesabına gir ve teslimat/fatura bilgilerini doldur. Sipariş özeti açıldığında ürünleri, adresleri ve tüm tutarları kontrol et. Geri dön düğmesiyle bilgileri düzeltebilirsin.',
 '3. Ön bilgilendirme ve mesafeli sözleşme nüshasını oku. Test siparişini onayla. Test ödeme ekranında başarı veya başarısızlık senaryosunu seç; gerçek para alınmaz.',
 '4. Hesabım > Siparişler bölümünden durum, kargo bilgisi, sözleşme nüshası ve taleplerine ulaş. Sipariş ve kabul kayıtları sunucuda saklanır; tarayıcı sepetinden bağımsızdır. Sözleşme dili Türkçedir. Hatalar ve sorular için İletişim sayfası kullanılabilir.']}
};
export function orderLegalText(snapshot){return ['TEST SİPARİŞİ — TAHSİLAT YOK', 'Sürüm: '+LEGAL_VERSION,'Satıcı: '+SELLER.name,SELLER.address,SELLER.email,'Alıcı: '+snapshot.customer.name,'E-posta: '+snapshot.customer.email,'Teslimat: '+JSON.stringify(snapshot.address),'Fatura: '+JSON.stringify(snapshot.billing),...snapshot.items.map(i=>i.name+' / '+i.size+' x '+i.qty+' = '+(i.qty*i.price_cents/100).toFixed(2)+' TL'),'Vergiler dahil ürün toplamı: '+(snapshot.subtotal_cents/100).toFixed(2)+' TL','Teslimat (örnek): '+(snapshot.shipping_cents/100).toFixed(2)+' TL','TOPLAM: '+(snapshot.total_cents/100).toFixed(2)+' TL',...['on-bilgilendirme','mesafeli-satis','cayma-iade'].flatMap(k=>[LEGAL_DOCS[k].title,...LEGAL_DOCS[k].paragraphs])].join('\n\n');}
