import {hash,hex,passwordHash,equal} from './access-api.js';
import {can} from '../public/permissions.js';
import {LEGAL_VERSION,LEGAL_DOCS,SELLER,orderLegalText} from './webshop-legal.js';
import {paymentRoutes,refundOrder,refundPlan} from './webshop-payment.js';
import {catalogRoutes} from './webshop-catalog.js';
import {accountRoutes,accountAdminRoutes,issueToken} from './webshop-account.js';
import {saleStatements} from './webshop-ledger.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})};
const now=()=>Math.floor(Date.now()/1000);
const json=(x,status=200,headers={})=>Response.json(x,{status,headers:{'Cache-Control':'no-store',...headers}});
const text=(x,label,max=200)=>{if(typeof x!=='string'||!x.trim()||x.length>max)fail(label+' alanını kontrol et.');return x.trim()};
const email=x=>{const e=text(x,'E-posta',254).toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(e))fail('E-posta geçersiz.');return e};
const integer=(x,min,max)=>{if(!Number.isSafeInteger(x)||x<min||x>max)fail('Adet veya tutar geçersiz.');return x};
export const demoEnabled=(request,env)=>env.WS_MODE==='demo'&&['localhost','127.0.0.1','[::1]'].includes(new URL(request.url).hostname);
async function expirePending(db){await db.batch([db.prepare("INSERT INTO ws_events(id,order_id,actor,action) SELECT lower(hex(randomblob(16))),id,'system','Ödeme testi süresi doldu; stok serbest bırakıldı' FROM ws_orders WHERE payment_status='pending' AND status='new' AND created_at<datetime('now','-30 minutes')"),db.prepare("UPDATE ws_orders SET payment_status='failed',status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE payment_status='pending' AND status='new' AND created_at<datetime('now','-30 minutes')")]);}
const requireDemo=(r,e)=>{if(!demoEnabled(r,e))fail('Mağaza henüz gerçek satışa açılmadı. Test ortamını kullanın.',503)};
const cookie=(r,t,seconds)=>`ws_customer=${t}; Path=/; HttpOnly; SameSite=Strict; Max-Age=${seconds}${new URL(r.url).protocol==='https:'?'; Secure':''}`;
async function customer(request,db){const t=request.headers.get('Cookie')?.match(/(?:^|;\s*)ws_customer=([a-f0-9]{64})(?:;|$)/)?.[1];if(!t)return null;return db.prepare('SELECT c.id,c.name,c.email,s.token_hash FROM ws_sessions s JOIN ws_customers c ON c.id=s.customer_id WHERE s.token_hash=? AND s.expires_at>?').bind(await hash(t),now()).first()}
const publicCustomer=c=>c?{id:c.id,name:c.name,email:c.email}:null;
async function limit(r,db,subject,max=15){await db.prepare('DELETE FROM login_limits WHERE reset_at<?').bind(now()).run();for(const [s,n] of [[subject,max],['ip:'+r.headers.get('CF-Connecting-IP'),60]]){const x=await db.prepare('INSERT INTO login_limits(key,attempts,reset_at) VALUES(?,1,?) ON CONFLICT(key) DO UPDATE SET attempts=attempts+1 RETURNING attempts').bind(await hash('webshop:'+s),now()+900).first();if(x.attempts>n)fail('Çok fazla deneme. 15 dakika sonra tekrar dene.',429)}}
function address(x){if(!x||typeof x!=='object')fail('Adres gerekli.');return {name:text(x.name,'Alıcı adı',100),phone:text(x.phone,'Telefon',30),city:text(x.city,'İl',60),district:text(x.district,'İlçe',80),line:text(x.line,'Açık adres',500)}}
const event=(db,id,actor,action)=>db.prepare('INSERT INTO ws_events(id,order_id,actor,action) VALUES(?,?,?,?)').bind(crypto.randomUUID(),id,actor,action);
function orderRow(o){if(!o)return null;const {snapshot_json,...rest}=o;return {...rest,snapshot:JSON.parse(snapshot_json)}}
async function ownOrder(db,id,cid){const o=await db.prepare('SELECT * FROM ws_orders WHERE id=? AND customer_id=?').bind(id,cid).first();if(!o)fail('Sipariş bulunamadı.',404);return o}
export async function storeApi(request,env,path,readBody){
 const db=env.DB,method=request.method,url=new URL(request.url),sub=path.slice('/api/store'.length);
 // Sağlayıcı ödemesi ayrı modüldedir; bu dosyanın akışı değişmez (src/webshop-payment.js).
 const payment=await paymentRoutes({request,env,sub,readBody,db,helpers:{customer,ownOrder,requireDemo,event,json,fail,limit,orderRow}});if(payment)return payment;
 if(sub==='/config'&&method==='GET')return json({mode:demoEnabled(request,env)?'demo':'closed',version:LEGAL_VERSION,seller:SELLER,shipping_cents:5900,live_ready:false,blockers:['KEP ve oda bilgileri teyit edilecek','Kargo, fiyat ve stok eşleştirmesi kesinleşecek','ETBİS ve kişisel veri aktarım/saklama süreci doğrulanacak','Ödeme, e-posta doğrulama ve sıfırlama sağlayıcıları bağlanacak']});
 if(sub==='/legal'&&method==='GET')return json({version:LEGAL_VERSION,seller:SELLER,documents:LEGAL_DOCS});
 if(sub==='/catalog'&&method==='GET')return json({items:(await db.prepare('SELECT id,product_id,name,size,image,category,price_cents,stock FROM ws_catalog WHERE active=1 ORDER BY name,size').all()).results});
 if(sub==='/auth/me'&&method==='GET')return json({customer:publicCustomer(await customer(request,db)),mode:demoEnabled(request,env)?'demo':'closed'});
 requireDemo(request,env);
 await expirePending(db);
 // Hesap güvenliği ve iletişim formu (src/webshop-account.js). Canlı kapısından SONRA: canlıda kapalı.
 const account=await accountRoutes({request,env,sub,readBody,db,helpers:{customer,hash,hex,now,passwordHash,email,text,fail,json,limit,cookie}});if(account)return account;
 if(['/auth/register','/auth/login'].includes(sub)&&method==='POST'){
  const x=await readBody(request),em=email(x.email);await limit(request,db,'auth:'+em);
  if(typeof x.password!=='string'||x.password.length<12||x.password.length>200)fail('Şifre 12–200 karakter olmalı.');
  let c=await db.prepare('SELECT * FROM ws_customers WHERE email=?').bind(em).first();
  if(sub==='/auth/register'){if(x.terms_version!==LEGAL_VERSION)fail('Güncel üyelik koşullarını kabul et.');if(c)fail('Bu e-posta ile işlem yapılamadı. Giriş yapmayı deneyin.',409);const id=crypto.randomUUID(),salt=crypto.randomUUID(),name=text(x.name,'Ad soyad',100);try{await db.prepare('INSERT INTO ws_customers(id,email,name,salt,password_hash) VALUES(?,?,?,?,?)').bind(id,em,name,salt,await passwordHash(x.password,salt)).run()}catch{fail('Bu e-posta ile işlem yapılamadı.',409)}c={id,email:em,name};await issueToken(db,{hash,hex,now},c,'verify_email',url.origin);
  }else{const check=await passwordHash(x.password,c?.salt||'missing-customer');if(!c||!equal(check,c.password_hash))fail('E-posta veya şifre hatalı.',401)}
  const token=hex(crypto.getRandomValues(new Uint8Array(32)));await db.batch([db.prepare('DELETE FROM ws_sessions WHERE expires_at<?').bind(now()),db.prepare('INSERT INTO ws_sessions(token_hash,customer_id,expires_at) VALUES(?,?,?)').bind(await hash(token),c.id,now()+604800)]);return json({customer:publicCustomer(c)},200,{'Set-Cookie':cookie(request,token,604800)});
 }
 const c=await customer(request,db);if(!c)fail('Mağaza hesabınla giriş yap.',401);
 if(sub==='/auth/logout'&&method==='POST'){await db.prepare('DELETE FROM ws_sessions WHERE token_hash=?').bind(c.token_hash).run();return json({ok:true},200,{'Set-Cookie':cookie(request,'',0)})}
 if(sub==='/auth/password'&&method==='POST'){const x=await readBody(request);await limit(request,db,'password:'+c.id,8);const saved=await db.prepare('SELECT salt,password_hash FROM ws_customers WHERE id=?').bind(c.id).first();if(typeof x.current!=='string'||x.current.length>200||!equal(await passwordHash(x.current,saved.salt),saved.password_hash))fail('Mevcut şifre hatalı.',401);if(typeof x.password!=='string'||x.password.length<12||x.password.length>200)fail('Yeni şifre 12–200 karakter olmalı.');const salt=crypto.randomUUID();await db.batch([db.prepare('UPDATE ws_customers SET salt=?,password_hash=? WHERE id=?').bind(salt,await passwordHash(x.password,salt),c.id),db.prepare('DELETE FROM ws_sessions WHERE customer_id=?').bind(c.id)]);return json({ok:true},200,{'Set-Cookie':cookie(request,'',0)})}
 if(sub==='/quote'&&method==='POST'){
  await limit(request,db,'quote:'+c.id,40);const x=await readBody(request);if(!Array.isArray(x.items)||!x.items.length||x.items.length>40)fail('Sepette 1–40 ürün olmalı.');const merged=new Map();
  for(const i of x.items){const id=text(i?.variant_id,'Ürün',120);merged.set(id,integer((merged.get(id)||0)+integer(i.qty,1,99),1,99))}
  const items=[];for(const [id,qty]of merged){const item=await db.prepare('SELECT * FROM ws_catalog WHERE id=? AND active=1').bind(id).first();if(!item||item.stock<qty)fail('Ürün veya yeterli stok bulunamadı.',409);items.push({variant_id:id,name:item.name,size:item.size,image:item.image,qty,price_cents:item.price_cents})}
  const subtotal=items.reduce((n,i)=>n+i.qty*i.price_cents,0);if(!Number.isSafeInteger(subtotal)||subtotal>100000000)fail('Sepet tutarı çok yüksek.');const shipping=5900;
  const snapshot={customer:publicCustomer(c),seller:SELLER,address:address(x.address),billing:x.same_billing===true?address(x.address):address(x.billing),items,subtotal_cents:subtotal,shipping_cents:shipping,total_cents:subtotal+shipping,legal_version:LEGAL_VERSION,is_test:true};snapshot.legal_text=orderLegalText(snapshot);
  const id=crypto.randomUUID();await db.prepare('INSERT INTO ws_quotes(id,customer_id,snapshot_json,expires_at) VALUES(?,?,?,?)').bind(id,c.id,JSON.stringify(snapshot),now()+900).run();return json({id,expires_at:now()+900,...snapshot});
 }
 if(sub==='/orders'&&method==='POST'){
  const x=await readBody(request);if(x.preinformation!==true||x.contract!==true||x.legal_version!==LEGAL_VERSION)fail('Ön bilgilendirme ve sözleşme kabulünü tamamla.');const q=await db.prepare('SELECT * FROM ws_quotes WHERE id=? AND customer_id=?').bind(text(x.quote_id,'Özet',80),c.id).first();if(!q)fail('Sipariş özeti bulunamadı.',404);
  const existing=await db.prepare('SELECT id,number FROM ws_orders WHERE quote_id=?').bind(q.id).first();if(existing)return json(existing);
  if(q.expires_at<now())fail('Özetin süresi doldu. Yeniden hesapla.',409);const s=JSON.parse(q.snapshot_json);if(s.legal_version!==LEGAL_VERSION)fail('Sözleşme sürümü değişti; özeti yenile.',409);const id=crypto.randomUUID(),number='TEST-'+id.slice(0,8).toUpperCase(),accepted=new Date().toISOString();
  try{await db.batch([db.prepare('INSERT INTO ws_orders(id,number,customer_id,quote_id,subtotal_cents,shipping_cents,total_cents,snapshot_json,legal_version,accepted_at) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,number,c.id,q.id,s.subtotal_cents,s.shipping_cents,s.total_cents,q.snapshot_json,LEGAL_VERSION,accepted),...s.items.map(i=>db.prepare('INSERT INTO ws_order_items(id,order_id,variant_id,name,size,qty,price_cents) VALUES(?,?,?,?,?,?,?)').bind(crypto.randomUUID(),id,i.variant_id,i.name,i.size,i.qty,i.price_cents)),event(db,id,c.id,'Test siparişi oluşturuldu; sözleşme kabulü kaydedildi')])}catch{const retry=await db.prepare('SELECT id,number FROM ws_orders WHERE quote_id=?').bind(q.id).first();if(retry)return json(retry);fail('Stok değişti veya kayıt tamamlanamadı. Sepeti yenile.',409)}return json({id,number},201);
 }
 if(sub==='/orders'&&method==='GET')return json({orders:(await db.prepare('SELECT id,number,status,payment_status,total_cents,is_test,created_at FROM ws_orders WHERE customer_id=? ORDER BY created_at DESC,id DESC LIMIT 100').bind(c.id).all()).results});
 const match=sub.match(/^\/orders\/([a-f0-9-]{36})(?:\/(document|demo-payment|cancel))?$/);
 if(match){const o=await ownOrder(db,match[1],c.id);
  if(method==='GET'&&!match[2])return json({...orderRow(o),events:(await db.prepare('SELECT action,created_at FROM ws_events WHERE order_id=? ORDER BY created_at,rowid').bind(o.id).all()).results});
  if(method==='GET'&&match[2]==='document')return json({filename:o.number+'-sozlesme.txt',text:'Sipariş: '+o.number+'\nKabul tarihi: '+o.accepted_at+'\n\n'+JSON.parse(o.snapshot_json).legal_text});
  if(method==='POST'&&match[2]==='demo-payment'){
   const x=await readBody(request);if(!['success','failure'].includes(x.outcome))fail('Test sonucu geçersiz.');if(o.payment_status==='demo_paid')return json({ok:true,payment_status:o.payment_status});if(o.status==='cancelled'||o.payment_status!=='pending')fail('Bu sipariş ödeme beklemiyor.',409);
   const result=await db.batch([db.prepare("UPDATE ws_orders SET payment_status=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND payment_status='pending' AND status='new' RETURNING id").bind(x.outcome==='success'?'demo_paid':'failed',x.outcome==='success'?'new':'cancelled',o.id),db.prepare('INSERT INTO ws_events(id,order_id,actor,action) SELECT ?,?,?,? WHERE changes()>0').bind(crypto.randomUUID(),o.id,c.id,'Test ödeme sonucu: '+x.outcome+' — gerçek tahsilat yok')]);if(!result[0].results.length)fail('Siparişin durumu değişti; yeniden kontrol et.',409);return json({ok:true});
  }
  if(method==='POST'&&match[2]==='cancel'){if(o.status==='cancelled')return json({ok:true});if(!['new','preparing','cancelled'].includes(o.status))fail('Kargoya verilen ürün için cayma talebi oluştur.',409);await db.batch([db.prepare("UPDATE ws_orders SET status='cancelled',updated_at=CURRENT_TIMESTAMP WHERE id=? AND status IN('new','preparing')").bind(o.id),event(db,o.id,c.id,'Test siparişi iptal edildi')]);return json({ok:true})}
 }
 if(sub==='/requests'&&method==='POST'){const x=await readBody(request);if(!['withdrawal','support','privacy'].includes(x.kind))fail('Talep türü geçersiz.');if(x.order_id)await ownOrder(db,text(x.order_id,'Sipariş',80),c.id);await limit(request,db,'request:'+c.id,20);const id=crypto.randomUUID();await db.prepare('INSERT INTO ws_requests(id,customer_id,order_id,kind,message) VALUES(?,?,?,?,?)').bind(id,c.id,x.order_id||null,x.kind,text(x.message,'Talep',2000)).run();return json({id},201)}
 if(sub==='/requests'&&method==='GET')return json({requests:(await db.prepare('SELECT id,order_id,kind,message,status,created_at FROM ws_requests WHERE customer_id=? ORDER BY created_at DESC LIMIT 100').bind(c.id).all()).results});
 fail('Bulunamadı.',404);
}
export async function webshopAdminApi(request,env,path,readBody,user){
 // Gerçek stok kartı eşlemesi ayrı modüldedir (src/webshop-catalog.js); bu dosyanın akışı değişmez.
 const catalog=await catalogRoutes({request,env,path,readBody,user,helpers:{requireDemo,event,fail}});if(catalog)return catalog;
 const accountAdmin=await accountAdminRoutes({request,env,path,readBody,user,helpers:{requireDemo,fail,can}});if(accountAdmin)return accountAdmin;
 const db=env.DB,sub=path.slice('/api/webshop'.length),method=request.method,url=new URL(request.url),page=Math.max(1,Math.min(10000,Number(url.searchParams.get('page'))||1)),offset=(Math.floor(page)-1)*50;
 if(sub==='/overview'&&method==='GET'){const stats=await db.prepare("SELECT COUNT(*) orders_count,COALESCE(SUM(CASE WHEN status='delivered' AND payment_status='demo_paid' THEN total_cents ELSE 0 END),0) delivered_cents,COALESCE(SUM(CASE WHEN payment_status='demo_paid' AND status<>'cancelled' THEN total_cents ELSE 0 END),0) demo_paid_cents,SUM(CASE WHEN status='new' THEN 1 ELSE 0 END) new_count FROM ws_orders").first();return {...stats,customers_count:(await db.prepare('SELECT COUNT(*) n FROM ws_customers').first()).n,requests_count:(await db.prepare("SELECT COUNT(*) n FROM ws_requests WHERE status<>'closed'").first()).n,mode:'demo',live_ready:false,notice:'Yalnızca test kayıtları. Gerçek tahsilat ve muhasebe fişi oluşturulmaz.'}}
 if(sub==='/orders'&&method==='GET'){const q='%'+(url.searchParams.get('q')||'').slice(0,100)+'%',status=url.searchParams.get('status')||'';const where="WHERE (o.number LIKE ? OR c.name LIKE ? OR c.email LIKE ?) AND (?='' OR o.status=?)";return {orders:(await db.prepare('SELECT o.id,o.number,o.status,o.payment_status,o.total_cents,o.created_at,o.is_test,c.name,c.email FROM ws_orders o JOIN ws_customers c ON c.id=o.customer_id '+where+' ORDER BY o.created_at DESC,o.id DESC LIMIT 50 OFFSET ?').bind(q,q,q,status,status,offset).all()).results,total:(await db.prepare('SELECT COUNT(*) n FROM ws_orders o JOIN ws_customers c ON c.id=o.customer_id '+where).bind(q,q,q,status,status).first()).n,page}}
 if(sub==='/customers'&&method==='GET'){const q='%'+(url.searchParams.get('q')||'').slice(0,100)+'%';return {customers:(await db.prepare('SELECT c.id,c.name,c.email,c.created_at,COUNT(o.id) orders_count FROM ws_customers c LEFT JOIN ws_orders o ON o.customer_id=c.id WHERE c.name LIKE ? OR c.email LIKE ? GROUP BY c.id ORDER BY c.created_at DESC,c.id LIMIT 50 OFFSET ?').bind(q,q,offset).all()).results,total:(await db.prepare('SELECT COUNT(*) n FROM ws_customers WHERE name LIKE ? OR email LIKE ?').bind(q,q).first()).n,page}}
 if(sub==='/catalog'&&method==='GET')return {items:(await db.prepare('SELECT * FROM ws_catalog ORDER BY name,size').all()).results};
 const product=sub.match(/^\/catalog\/([\w-]+)$/);
 if(product&&method==='POST'){if(!user.owner)fail('Katalog ayarlarını yönetici değiştirebilir.',403);requireDemo(request,env);const x=await readBody(request);await db.batch([db.prepare('UPDATE ws_catalog SET price_cents=?,stock=?,active=? WHERE id=?').bind(integer(x.price_cents,1,10000000),integer(x.stock,0,100000),x.active===true?1:0,product[1]),event(db,null,user.id,'Test katalog fiyat/stok düzenlendi: '+product[1])]);return {ok:true}}
 const refund=sub.match(/^\/orders\/([a-f0-9-]{36})\/refund$/);
 // Sandbox iadesi: yalnızca yönetici, yalnızca yerel demo. Gerçek para hareketi ve defter kaydı yok.
 if(refund&&method==='POST'){if(!user.owner)fail('İadeyi yönetici başlatabilir.',403);requireDemo(request,env);const row=await db.prepare('SELECT * FROM ws_orders WHERE id=?').bind(refund[1]).first();if(!row)fail('Sipariş bulunamadı.',404);return await refundOrder(db,env,{order:row,actor:user.id||'owner',ip:request.headers.get('CF-Connecting-IP')||'127.0.0.1'})}
 const match=sub.match(/^\/orders\/([a-f0-9-]{36})$/);
 if(match){const row=await db.prepare('SELECT * FROM ws_orders WHERE id=?').bind(match[1]).first();if(!row)fail('Sipariş bulunamadı.',404);
  if(method==='GET'){const o=orderRow(row),amounts=can(user,'ec','amounts'),plan=await refundPlan(db,o.id),refunds=(await db.prepare('SELECT item_id,amount_cents,status,reason,created_at FROM ws_refunds WHERE order_id=? ORDER BY created_at,rowid').bind(o.id).all()).results;if(!amounts)delete o.snapshot.legal_text;return {...o,payment:plan.payment?{status:plan.payment.status,...(amounts?{amount_cents:plan.payment.verified_cents}:{})}:null,refunds:amounts?refunds:refunds.map(({amount_cents,...r})=>r),refundable:row.status==='cancelled'&&!!plan.payment&&plan.items.length>0&&plan.todo.length>0&&!plan.pending.length,events:(await db.prepare('SELECT actor,action,created_at FROM ws_events WHERE order_id=? ORDER BY created_at,rowid').bind(o.id).all()).results}}
  if(method==='POST'){requireDemo(request,env);const x=await readBody(request),allowed={new:['preparing','cancelled'],preparing:['shipped','cancelled'],shipped:['delivered'],delivered:[],cancelled:[]};if(!allowed[row.status].includes(x.status))fail('Durum geçişi geçersiz.',409);if(x.status!=='cancelled'&&row.payment_status!=='demo_paid')fail('Ödeme testini tamamlamadan sevk yapılamaz.',409);const carrier=x.status==='shipped'?text(x.carrier,'Kargo firması',100):row.carrier,tracking=x.status==='shipped'?text(x.tracking,'Takip numarası',100):row.tracking;// Canlı siparişte sevk = e-ticaret defterine satış (src/webshop-ledger.js). Test siparişi deftere yazılmaz.
  const ledger=x.status==='shipped'&&row.is_test===0?await saleStatements(db,row,new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Istanbul'})):[];let result;try{result=await db.batch([db.prepare('UPDATE ws_orders SET status=?,carrier=?,tracking=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND status=? RETURNING id').bind(x.status,carrier,tracking,row.id,row.status),event(db,row.id,user.id,'Durum: '+x.status),...ledger])}catch(e){if(/INSUFFICIENT_STOCK|STOCK_RESERVED|INVALID_STOCK_VALUE/.test(String(e.message)))fail('Gerçek stok yetersiz; sevk ve satış kaydı yapılmadı.',409);throw e}if(!result[0].results.length)fail('Sipariş değişti; yenile.',409);return {ok:true}}
 }
 if(sub==='/requests'&&method==='GET')return {requests:(await db.prepare('SELECT r.*,c.name,c.email,o.number FROM ws_requests r JOIN ws_customers c ON c.id=r.customer_id LEFT JOIN ws_orders o ON o.id=r.order_id ORDER BY r.created_at DESC,r.id LIMIT 50 OFFSET ?').bind(offset).all()).results,page,total:(await db.prepare('SELECT COUNT(*) n FROM ws_requests').first()).n};
 const req=sub.match(/^\/requests\/([a-f0-9-]{36})$/);if(req&&method==='POST'){requireDemo(request,env);const x=await readBody(request);if(!['open','reviewing','closed'].includes(x.status))fail('Geçersiz durum.');await db.batch([db.prepare('UPDATE ws_requests SET status=? WHERE id=?').bind(x.status,req[1]),event(db,null,user.id,'Talep '+req[1]+' → '+x.status)]);return {ok:true}}
 fail('Bulunamadı.',404);
}
